# WARNING - Generated by {fusen} from /dev/flat_full.Rmd: do not edit by hand

#' @title get data from RIDL
#'
#' @param dataraw folder where to put the data
#' @return  progresobj  a list with all required frame
#'
#' @export 

#' @examples
#' 
#' #progresobj <- data_load(dataraw = "data-raw")
#' 
#' progresobj <- data_load(dataraw = system.file("demo/", package = "proGresAnalysis") )
#' 
#' 
data_load <- function(dataraw = "data-raw" ) {
 
     Individual <- readr::read_csv(here::here(dataraw, "Individual.csv"))
 
     RegistrationGroup <- readr::read_csv(here::here(dataraw, "RegistrationGroup.csv")) 
  
    # Address <- readr::read_csv(here::here(dataraw, "Address.csv"), progress = TRUE) 
     Assistance <- readr::read_csv(here::here(dataraw, "Assistance.csv"), progress = TRUE) 
     #Assistance <- utils::read.csv(here::here(dataraw, "Assistance.csv"), encoding = "UTF-8", na.strings = "") 
     #Assistance <- utils::read.csv(here::here(dataraw, "Assistance.csv")) 
  
     Document <- readr::read_csv(here::here(dataraw, "Document.csv")) 
  
     Education <- readr::read_csv(here::here(dataraw, "Education.csv"))
  
    EntitlementCard <- readr::read_csv(here::here(dataraw, "EntitlementCard.csv")) 
    
    IndividualProperty <- readr::read_csv(here::here(dataraw, "IndividualProperty.csv"))
    
    Language <- readr::read_csv(here::here(dataraw, "Language.csv"))
    
    Nationality <- readr::read_csv(here::here(dataraw, "Nationality.csv")) 
    
    Relative <- readr::read_csv(here::here(dataraw, "Relative.csv"))
    
    Representative <- readr::read_csv(here::here(dataraw, "Representative.csv"))
    
    Skill <- readr::read_csv(here::here(dataraw, "Skill.csv"))
    
    SocioEconomic <- readr::read_csv(here::here(dataraw, "SocioEconomic.csv"))
    
    SpecificNeed <- readr::read_csv(here::here(dataraw, "SpecificNeed.csv")) 
    #SpecificNeed <- utils::read.csv(here::here(dataraw, "SpecificNeed.csv"), encoding = "UTF-8", na.strings = "") 
    
    Transit <- readr::read_csv(here::here(dataraw, "Transit.csv")) 
    
    WorkExperience <- readr::read_csv(here::here(dataraw, "WorkExperience.csv"), 
        ## some encoding issue to addres... it's not expected UTF-8..
        locale = readr::locale(encoding = "UTF-16"))
  
 
 progresobj <- list(
     Individual,
     RegistrationGroup,
     Assistance, 
     Document,
     Education , 
    EntitlementCard,
    IndividualProperty , 
    Language , 
    Nationality ,
    Relative , 
    Representative, 
    Skill, 
    SocioEconomic ,
    SpecificNeed ,
    Transit ,
    WorkExperience  )
 
    rm(
     Individual,
     RegistrationGroup,
     Assistance, 
     Document,
     Education , 
    EntitlementCard,
    IndividualProperty , 
    Language , 
    Nationality ,
    Relative , 
    Representative, 
    Skill, 
    SocioEconomic ,
    SpecificNeed ,
    Transit ,
    WorkExperience  )
    return(progresobj)

     
     ## remotes::install_github("galalH/riddle")
     # library("riddle")
     # url <- "https://ridl.unhcr.org/dataset/brazil-registration-data-february-2022"
     # 
     # riddle::resource_fetch(url, path = here::here("data-raw2"))
}

