# WARNING - Generated by {fusen} from /dev/flat_full.Rmd: do not edit by hand

#' @title get data from RIDL
#'
#' @param ridldataset name of the project in ridl.unhcr.org, the internal UNHCR repository based on CKAN
#' @param dataraw folder where to put the data
#'
#' @export 

#' @examples
#' 
#' # data_get(ridldataset = "xxxx", dataraw = "data-raw")
#' 
data_get <- function(ridldataset,
                     dataraw = "data-raw") {
  # remotes::install_gitlab("dickoa/ridl")
  ## Note that you need to set up your environment variable first
  require(ridl)
 #  ridl::ridl_config_get()
 #  
 #  library(tidyverse)
 #  ridl::ridl_dataset_search("registration") 
 ridldatasets <- ridl::ridl_dataset_show(ridldataset)
  
 # Create "data-raw" folder if it does not exist
 if (!dir.exists(here::here(dataraw))) {dir.create(here::here(dataraw))}
 # And now get all ressources there
 lapply(ridl::ridl_dataset_resource_get_all(ridldatasets),
        \(r) 
        ridl::ridl_resource_download(r, 
                                     folder = here::here(dataraw)) )
 ## get all the zip files and unzip them in the same folder
 filelist <- list.files(here::here(dataraw), pattern = ".zip", recursive = F)
 plyr::ldply(.data = here::here(dataraw,filelist), .fun = unzip,
             exdir = here::here(dataraw))
}
 
