# WARNING - Generated by {fusen} from /dev/flat_full.Rmd: do not edit by hand

#' @title Assemble all data components in a list and compute indicators
#' @description The function compute a summary chart 
#' @param progres   a list with all required frame re-encoded
#' @param ctr Country or Business Unit for the dataset dump
#' @param year Year of reference
#' @param ridl  name of the project in ridl.unhcr.org, the internal UNHCR repository based on CKAN
#' @return a list with both a ggplot2 crafted chart and the summary data
#' @export 
#' @examples
#' 
#' # progresobj <- data_load(dataraw = system.file("demo/", package = "proGresAnalysis") )
#' # progres <- data_recode(progresobj = progresobj,  ctr = "Ecuador")
#' 
#' # plot_assist_cashtarget(progres = progres,
#' #                                     ctr = "Ecuador",
#' #                                     ridl = "data-should-be-on-ridl",
#' #                                     thisyear = 2021 )
plot_assist_cashtarget  <- function(progres,
                                    ctr, 
                                    ridl = "data-should-be-on-ridl",
                                    thisyear = 2021 ) {
  
RegistrationGroupall <-  as.data.frame(progres[17]) 

#names(RegistrationGroupall)
model_logitCash <- glm(assistance_cash_bol ~
          ## test predictors below
                      group_size1 + 
                      ratio_female_cat + 
                     ratio_dependant_cat + 
                     sex_fp + 
                     age_avg_cat + 
                     age_sd_cat + 
                     divorced_separated_widow + 
                     single_adult + 
                     married_engaged +
                     single_minor + 
                     child_at_risk +
                     disability + 
                     serious_medical_condition +
                     sgbv,  
                     
                   data= RegistrationGroupall, 
                   family = binomial)  |> 
  ## stepwise indicator selection
  # http://www.sthda.com/english/articles/36-classification-methods-essentials/150-stepwise-logistic-regression-essentials-in-r/
  MASS::stepAIC(trace = FALSE) 

#broom::tidy(model_logit)


# https://www.youtube.com/watch?v=C4N3_XJJ-jU
far <- model_logitCash$null.deviance/-2 ## McFadden's Pseudo R2
ll <- model_logitCash$deviance/-2 ## log -likelihood for the fancy model
r2 <- (far -ll) / far ## Pseudo R2
pval <-  1- pchisq(2*(ll- far), df=(length(model_logitCash$coefficients)-1))  # pvalue

tidy_forestCash <-
  model_logitCash |>
  # perform initial tidying of the model
  broom.helpers::tidy_and_attach(exponentiate = TRUE, conf.int = TRUE) |>
  # adding in the reference row for categorical variables
  broom.helpers::tidy_add_reference_rows() |>
  # adding a reference value to appear in plot
  broom.helpers::tidy_add_estimate_to_reference_rows() |>
  # adding the variable labels
  broom.helpers::tidy_add_term_labels() |>
  # removing intercept estimate from model
  broom.helpers::tidy_remove_intercept()



tidy_forestCash2 <- tidy_forestCash |>
  # removing variable if pvalue are more than 0.4
  dplyr::filter( p.value < 0.3)

#tidy_forest

p <- tidy_forestCash2 |>
  mutate(
    plot_label = paste(var_label, label, sep = ":") |> 
      forcats::fct_inorder() |>
      forcats::fct_rev()
  ) |>
  ggplot(aes(x = plot_label, 
             y = estimate, 
             ymin = conf.low, 
             ymax = conf.high, 
             color = variable)) +
  geom_hline(yintercept = 1, linetype = 2) +
  geom_pointrange() +
  coord_flip() +
  theme(legend.position = "none") +    
  geom_hline(yintercept = 0, size = 1.1, colour = "#333333") +
  unhcrthemes::theme_unhcr( font_size= 18)  +  
  theme(panel.grid.major.x  = element_line(color = "#cbcbcb"), 
        panel.grid.major.y  = element_blank(), 
        panel.grid.minor = element_blank(), 
        axis.text.y = element_text(size = 10)) +
  labs(
    y = "Odds Ratio",
    x = " ",
    title = "What are the criteria predicting those receiving cash assistance?",
    subtitle = paste0("Regression analysis based on records in ", ctr, " analysed at case level."),
    caption = paste0("Source: Data available in RIDL @ ", ridl,"\n",
              str_wrap( "An odds ratio measures the association between a predictor variable (x) and the outcome variable (y). It represents the ratio of the odds that an event will occur (event = 1) given the presence of the predictor x (x = 1), compared to the odds of the event occurring in the absence of that predictor (x = 0).",180),
              "\n",
              str_wrap( paste0("McFadden's Pseudo R2 is ", far, 
                          "; log -likelihood for the fancy model is ", ll,
                          "; Pseudo R2 is ", r2,
                          " and its p-value is ", pval),180) ))

return(p)
}


#' @title Assemble all data components in a list and compute indicators
#' @description The function compute a summary chart 
#' @param progres   a list with all required frame re-encoded
#' @param ctr Country or Business Unit for the dataset dump
#' @param year Year of reference
#' @param ridl  name of the project in ridl.unhcr.org, the internal UNHCR repository based on CKAN
#' @return a list with both a ggplot2 crafted chart and the summary data
#' @export 
#' @examples
#' 
#' plot_assist_combin(progres = progres,
#'                                     ctr = "Ecuador",
#'                                     ridl = "data-should-be-on-ridl",
#'                                     thisyear = 2021 )
#' 
plot_assist_combin  <- function(progres,
                                    ctr, 
                                    ridl = "data-should-be-on-ridl",
                                    thisyear = 2021 ) { 
  
  

Individual <- as.data.frame(progres[1] ) 
Assistance <-  as.data.frame(progres[3] )
 RegistrationGroupall <-  as.data.frame(progres[17]) 

topAssistanceSub <- as.vector(as.data.frame(Assistance |> 
  dplyr::left_join( y = Individual,
                     by = c("IndividualID", "RegistrationGroupID")) |> 
  dplyr::group_by( RegistrationGroupID, AssistanceSub   ) |> 
  dplyr::summarise(n = dplyr::n()) |> 
  dplyr::filter( ! (is.na(AssistanceSub) ))  |> 
  dplyr::filter( ! (is.na(RegistrationGroupID) ))   |> 
  dplyr::group_by( AssistanceSub  ) |> 
  dplyr::summarise(uniquecase = dplyr::n())  |>    
  dplyr::arrange(desc(uniquecase)) |>
  head(15) |>
  dplyr::select(AssistanceSub)   )) |>
  as.data.frame() |>
  dplyr::pull()

d1 <- Assistance |> 
  dplyr::filter(AssistanceSub  %in%  topAssistanceSub ) |>
  #filter( AssistanceYear == 2020) |> 
  dplyr::left_join( y = Individual,
                    by = c("IndividualID", "RegistrationGroupID")) |> 
  dplyr::group_by( RegistrationGroupID, AssistanceSub   ) |> 
  dplyr::summarise(n = dplyr::n()) |> 
 dplyr::filter( ! (is.na(RegistrationGroupID) ))  |>
  tidyr::pivot_wider(names_from  = AssistanceSub,
                     values_from = n)
d <- d1  |> 
  dplyr::mutate( dplyr::across(where(is.integer), ~ tidyr::replace_na(.x, 0)) )
  #replace(is.na(.), 0)
  ## Remove identifiers
d2 <- d  |>
  dplyr::ungroup() |>
  dplyr::select( - 1 )  

corrMat <- round(cor(d2), 1)
p.mat <- ggcorrplot::cor_pmat(d2)
#corrr::correlate(d2) 

p <- ggcorrplot::ggcorrplot(  corrMat  ,
           hc.order = TRUE,
           type = "lower",
            method = "circle",
           outline.col = "white",
           ggtheme = ggplot2::theme_gray,
           colors = c("#6D9EC1", "white", "#E46726") ,
           ## cross if not significant
            p.mat = p.mat) + 
   guides(fill= "none") +
  unhcrthemes::theme_unhcr( font_size= 12)  +  
   theme(axis.text.x = element_text(size = 8, angle = 40,  hjust=1),
        axis.text.y = element_text(size = 8) ) +
  labs(
    y = "",
    x = " ",
    title = paste0("How much different types of Assistance aggregated at Case level are associated in ", ctr, "?"),
    subtitle = str_wrap( 
      "Correlation analysis: Red color indicate a positive association, while blue a negative one. The bigger the dot, the stronger the association, cross indicates the absence of significative association",
      180) ,
    caption = paste0("Source: Data available in RIDL @ ", ridl, "")
  )
return(p)


# 
# # Create a tidy data frame of correlations
# tidy_cors <-  d2 |> 
#   corrr::correlate()  |> 
#   corrr::stretch()
# 
# # Convert correlations stronger than some value
# # to an undirected graph object
# graph_cors <- tidy_cors |>
#  dplyr::filter(abs(r) > .2) |>
#   igraph::graph_from_data_frame(directed = FALSE)
# 
# # Plot
# ggraph(graph_cors) +
#   geom_edge_link(aes(edge_alpha = abs(r),
#                      edge_width = abs(r), 
#                      color = r)) +
#   guides(edge_alpha = "none", 
#          edge_width = "none") +
#   scale_edge_colour_gradientn(limits = c(-1, 1), 
#                               # colors = c("firebrick2",
#                               #            "dodgerblue2")
#                               colors = c("blue", "gray90",  "red")
#   ) +
#   geom_node_point(color = "gray90", 
#                   size = 7) +
#   geom_node_text(aes(label = name), 
#                  repel = TRUE) + 
#   unhcrthemes::theme_unhcr( font_size= 18)  +  
#   theme(panel.grid.major.x  = element_blank(), 
#         panel.grid.major.y  = element_blank(), 
#         panel.grid.minor = element_blank(), 
#         axis.text.x =  element_blank(), 
#         axis.text.y = element_blank(), 
#         legend.key.height= unit(0.5, 'cm'),
#         legend.key.width= unit(3, 'cm') ) +
#   labs(
#     y = "",
#     x = " ",
#     title = paste0("How much different types of Assistance aggregated at Case level are associated in ", ctr, "?"),
#     subtitle = paste0("Correlation analysis: Red color indicate a positive association, while blue a negative one "),
#     caption = paste0("Source: Data available in RIDL @ ", ridl, 
#                      "")
#   )
}


#' @title Assemble all data components in a list and compute indicators
#' @description The function compute a summary chart 
#' @param progres   a list with all required frame re-encoded
#' @param ctr Country or Business Unit for the dataset dump
#' @param year Year of reference
#' @param ridl  name of the project in ridl.unhcr.org, the internal UNHCR repository based on CKAN
#' @return a list with both a ggplot2 crafted chart and the summary data
#' @export 
#'
#' @examples
#' 
#' # progresobj <- data_load(dataraw = system.file("demo/", package = "proGresAnalysis") )
#' # progres <- data_recode(progresobj = progresobj,  ctr = "Ecuador")
#' plot_assist_evol(progres = progres,
#'                                     ctr = "Ecuador",
#'                                     ridl = "data-should-be-on-ridl",
#'                                     thisyear = 2021 )
#' 
plot_assist_evol  <- function(progres,
                                    ctr, 
                                    ridl = "data-should-be-on-ridl",
                                    thisyear = 2021 ) { 

Individual <- as.data.frame(progres[1] ) 
Assistance <-  as.data.frame(progres[3] )
     RegistrationGroupall <-  as.data.frame(progres[17]) 

topAssistanceSub <- as.vector(as.data.frame(Assistance |> 
                                              dplyr::left_join( y = Individual,
                                                                by = c("IndividualID", "RegistrationGroupID")) |> 
                                              dplyr::group_by( RegistrationGroupID, AssistanceSub   ) |> 
                                              dplyr::summarise(n = dplyr::n()) |> 
                                             dplyr::filter( ! (is.na(AssistanceSub) ))  |> 
                                             dplyr::filter( ! (is.na(RegistrationGroupID) ))   |> 
                                              dplyr::group_by( AssistanceSub  ) |> 
                                              dplyr::summarise(uniquecase = dplyr::n())  |>    
                                              dplyr::arrange(desc(uniquecase)) |>
                                              head(15) |>
                                              dplyr::select(AssistanceSub)   )) |>
                                              as.data.frame() |>
                                               dplyr::pull()



p <- Assistance |>   
  dplyr::filter(AssistanceSub  %in%  topAssistanceSub ) |>
  dplyr::left_join( y = Individual,
                    by = c("IndividualID", "RegistrationGroupID")) |> 
  dplyr::group_by( RegistrationGroupID, AssistanceSub, AssistanceYear   ) |> 
  dplyr::summarise(n = dplyr::n())  |> 
 dplyr::filter( ! (is.na(RegistrationGroupID) ))   |> 
 dplyr::filter( ! (is.na(AssistanceSub) ))  |> 
  dplyr::group_by( AssistanceSub, AssistanceYear  ) |> 
  dplyr::summarise(uniquecase = n())  |> 
  
  dplyr::left_join(
    Assistance |> 
      dplyr::filter(AssistanceSub  %in%  topAssistanceSub ) |>
      dplyr::left_join( y = Individual,
                        by = c("IndividualID", "RegistrationGroupID")) |> 
      dplyr::group_by( RegistrationGroupID, AssistanceSub, AssistanceYear    ) |> 
      dplyr::summarise(n = dplyr::n()) |> 
     dplyr::filter( ! (is.na(AssistanceSub) ))  |> 
     dplyr::filter( ! (is.na(RegistrationGroupID) ))   |> 
      dplyr::group_by( AssistanceSub, AssistanceYear   ) |> 
      dplyr::summarise(totalind = sum(n))
  ) |> 
  dplyr::mutate(avgindpercase = totalind/uniquecase)     |>
  dplyr::mutate(totalcase = nlevels(as.factor(Individual$RegistrationGroupID)))  |>
  dplyr::mutate(assistcover = uniquecase/totalcase)    |>
  dplyr::filter(AssistanceYear >= 2019 )     |>
  dplyr::filter( !(is.na(AssistanceYear)) )     |>
  mutate(uniquecase = as.numeric(uniquecase), 
         nRound =  ifelse(uniquecase > 1000, 
                          paste(scales::label_number_si(accuracy = 0.1)(uniquecase)),
                          as.character(uniquecase) ) ) |>  
  ggplot( aes(x = reorder(AssistanceSub,uniquecase), 
              y = uniquecase )) + 
  geom_bar(stat = "identity", 
           fill = "#0072bc") + 
  coord_flip() + 
  facet_grid(. ~ AssistanceYear  ) +
  scale_y_continuous( label = scales::label_number_si() ) + 
  ## Position label differently in the bar in white - outside bar in black
  geom_label( data =   function(x) subset(x, uniquecase < max(uniquecase) / 1.5),
              aes(x = reorder(AssistanceSub, uniquecase),
                  y = uniquecase,
                  label= nRound),
              hjust = -0.1 ,
              vjust = 0.5, 
              colour = "black", 
              fill = NA, 
              label.size = NA, 
              family = "Lato", 
              size = 4   ) +  
  
  geom_label( data =   function(x) subset(x, uniquecase >= max(uniquecase) / 1.5),
              aes(x = reorder(AssistanceSub, uniquecase),
                  y = uniquecase,
                  label= nRound),
              hjust = 1.1 ,
              vjust = 0.5, 
              colour = "white", 
              fill = NA, 
              label.size = NA, 
              family = "Lato", 
              size = 4   ) +   
  geom_hline(yintercept = 0, size = 1.1, colour = "#333333") +
  unhcrthemes::theme_unhcr( font_size= 18)  +  
  theme(panel.grid.major.x  = element_line(color = "#cbcbcb"), 
        panel.grid.major.y  = element_blank(), 
        panel.grid.minor = element_blank()) + 
  labs(title = paste0("How Assistance assistance intervention changed in ", ctr, "?"),
       subtitle = paste0("Evolution since 2019 for top 15 most frequent types of intervention"),   
       x = "",
       y = "",
       caption = paste0("Source: Data available in RIDL @ ", ridl, "\n Record are counted as single occurence per type at case level.") )
return(p)

}


#' @title Assemble all data components in a list and compute indicators
#' @description The function compute a summary chart 
#' @param progres   a list with all required frame re-encoded
#' @param ctr Country or Business Unit for the dataset dump
#' @param year Year of reference
#' @param ridl  name of the project in ridl.unhcr.org, the internal UNHCR repository based on CKAN
#' @return a list with both a ggplot2 crafted chart and the summary data
#' @export 
#'
#'

#' @examples
#' 
#' # progresobj <- data_load(dataraw = system.file("demo/", package = "proGresAnalysis") )
#' # progres <- data_recode(progresobj = progresobj,  ctr = "Ecuador")
#' # plot_assist_nothing (progres = progres,
#' #                                     ctr = "Ecuador",
#' #                                     ridl = "data-should-be-on-ridl",
#' #                                     thisyear = 2021 ) 
#' 
plot_assist_nothing  <- function(progres,
                                    ctr, 
                                    ridl = "data-should-be-on-ridl",
                                    thisyear = 2021 ) { 
  
 RegistrationGroupall <-  as.data.frame(progresobj[17]) 
 # names(RegistrationGroupall)
 # table( RegistrationGroupall$got_assistance, useNA = "ifany")
 
 
 model_logit <- glm(got_assistance ~ 
          ## test predictors below
                      group_size1 + 
                      ratio_female_cat + 
                     ratio_dependant_cat + 
                     sex_fp + 
                     age_avg_cat + 
                     age_sd_cat + 
                     divorced_separated_widow + 
                     single_adult + 
                     married_engaged +
                     single_minor + 
                     child_at_risk +
                     disability + 
                     serious_medical_condition +
                     sgbv,  
                   data= RegistrationGroupall, 
                   family = binomial)  |> 
  ## stepwise indicator selection
  # http://www.sthda.com/english/articles/36-classification-methods-essentials/150-stepwise-logistic-regression-essentials-in-r/
  MASS::stepAIC(trace = FALSE) 

#broom::tidy(model_logit)




## Key indicator on model
# https://www.youtube.com/watch?v=C4N3_XJJ-jU
far <- model_logit$null.deviance/-2 ## McFadden's Pseudo R2
ll <- model_logit$deviance/-2 ## log -likelihood for the fancy model
r2 <- (far -ll) / far ## Pseudo R2
pval <-  1- pchisq(2*(ll- far), df=(length(model_logit$coefficients)-1))  # pvalue


tidy_forest <-
  model_logit |>
  # perform initial tidying of the model
  broom.helpers::tidy_and_attach(exponentiate = TRUE, conf.int = TRUE) |>
  # adding in the reference row for categorical variables
  broom.helpers::tidy_add_reference_rows() |>
  # adding a reference value to appear in plot
  broom.helpers::tidy_add_estimate_to_reference_rows() |>
  # adding the variable labels
  broom.helpers::tidy_add_term_labels() |>
  # removing intercept estimate from model
  broom.helpers::tidy_remove_intercept()
#tidy_forest


tidy_forest2 <- tidy_forest |>
  # removing variable if pvalue are more than 0.4
  dplyr::filter( p.value < 0.3)


p <- tidy_forest2 |>
  mutate(
    plot_label = paste(var_label, label, sep = ":") |> 
      forcats::fct_inorder() |>
      forcats::fct_rev() ) |>
  ggplot(aes(x = plot_label, 
             y = estimate, 
             ymin = conf.low, 
             ymax = conf.high, 
             color = variable)) +
  geom_hline(yintercept = 1, linetype = 2) +
  geom_pointrange() +
  coord_flip() +
  theme(legend.position = "none") +    
  geom_hline(yintercept = 0, size = 1.1, colour = "#333333") +
  unhcrthemes::theme_unhcr( font_size= 18)  +  
  theme(panel.grid.major.x  = element_line(color = "#cbcbcb"), 
        panel.grid.major.y  = element_blank(), 
        panel.grid.minor = element_blank(),  
        axis.text.y = element_text(size = 10)) +
  labs(
    y = "Odds Ratio",
    x = " ",
    title = "Factors predicting Cases that did not get records Assistance",
    subtitle = paste0("Regression analysis "),
    caption = paste0("Source: Data available in RIDL @ ", ridl, "\n",
         str_wrap( "An odds ratio measures the association between a predictor variable (x) and the outcome variable (y). It represents the ratio of the odds that an event will occur (event = 1) given the presence of the predictor x (x = 1), compared to the odds of the event occurring in the absence of that predictor (x = 0).",180),"\n",
              "\n",
              str_wrap( paste0("McFadden's Pseudo R2 is ", far, 
                          "; log -likelihood for the fancy model is ", ll,
                          "; Pseudo R2 is ", r2,
                          " and its p-value is ", pval),180) ))
return(p)
}

#' @title Assemble all data components in a list and compute indicators
#' @description The function compute a summary chart 
#' @param progres   a list with all required frame re-encoded
#' @param ctr Country or Business Unit for the dataset dump
#' @param year Year of reference
#' @param ridl  name of the project in ridl.unhcr.org, the internal UNHCR repository based on CKAN
#' @return a list with both a ggplot2 crafted chart and the summary data
#' @export 
#'
#'

#' @examples
#' 
#' # progresobj <- data_load(dataraw = system.file("demo/", package = "proGresAnalysis") )
#' # progres <- data_recode(progresobj = progresobj,  ctr = "Ecuador")
#' plot_assist_type (progres = progres,
#'                                     ctr = "Ecuador",
#'                                     ridl = "data-should-be-on-ridl",
#'                                     thisyear = 2021 ) 
plot_assist_type <- function(progres,
                                    ctr, 
                                    ridl = "data-should-be-on-ridl",
                                    thisyear = 2021 ) { 
  
  

Individual <- as.data.frame(progres[1] ) 
Assistance <-  as.data.frame(progres[3] )
     RegistrationGroupall <-  as.data.frame(progres[17]) 
  
p <- Assistance |> 
  #filter( AssistanceYear == 2020) |> 
  dplyr::left_join( y = Individual,
                    by = c("IndividualID", "RegistrationGroupID")) |> 
  dplyr::group_by( RegistrationGroupID, AssistanceSub   ) |> 
  dplyr::summarise(n = dplyr::n()) |> 
 dplyr::filter( ! (is.na(RegistrationGroupID) ))   |> 
 dplyr::filter( ! (is.na(AssistanceSub) ))  |> 
  dplyr::group_by( AssistanceSub  ) |> 
  dplyr::summarise(uniquecase = n())   |> 
  
  dplyr::left_join(Assistance |> 
                     #dplyr::filter( AssistanceYear == 2020) |> 
                     dplyr::left_join( y = Individual,
                                       by = c("IndividualID", "RegistrationGroupID")) |> 
                     dplyr::group_by( RegistrationGroupID, AssistanceSub   ) |> 
                     dplyr::summarise(n = dplyr::n()) |> 
                    dplyr::filter( ! (is.na(AssistanceSub) ))  |> 
                    dplyr::filter( ! (is.na(RegistrationGroupID) ))   |> 
                     dplyr::group_by( AssistanceSub  ) |> 
                     dplyr::summarise(totalind = sum(n)) )  |> 
  dplyr::mutate(avgindpercase = totalind/uniquecase)     |>
  dplyr::mutate(totalcase = nlevels(as.factor(Individual$RegistrationGroupID)))  |>
  dplyr::mutate(assistcover = uniquecase/totalcase)     |>
  dplyr::filter(assistcover >= 0.01 )     |>
  mutate(uniquecase = as.numeric(uniquecase), 
         nRound =  ifelse(uniquecase > 1000, 
                          paste(scales::label_number_si(accuracy = 0.1)(uniquecase)),
                          as.character(uniquecase) ) ) |>  
  ggplot( aes(x = reorder(AssistanceSub,uniquecase), 
              y = uniquecase )) + 
  geom_bar(stat = "identity", 
           fill = "#0072bc") + 
  coord_flip() + 
  scale_y_continuous( label = scales::label_number_si() ) + 
  ## Position label differently in the bar in white - outside bar in black
  geom_label( data =   function(x) subset(x, uniquecase < max(uniquecase) / 1.5),
              aes(x = reorder(AssistanceSub, uniquecase),
                  y = uniquecase,
                  label= nRound),
              hjust = -0.1 ,
              vjust = 0.5, 
              colour = "black", 
              fill = NA, 
              label.size = NA, 
              family = "Lato", 
              size = 4   ) +  
  
  geom_label( data =   function(x) subset(x, uniquecase >= max(uniquecase) / 1.5),
              aes(x = reorder(AssistanceSub, uniquecase),
                  y = uniquecase,
                  label= nRound),
              hjust = 1.1 ,
              vjust = 0.5, 
              colour = "white", 
              fill = NA, 
              label.size = NA, 
              family = "Lato", 
              size = 4   ) +   
  geom_hline(yintercept = 0, size = 1.1, colour = "#333333") +
  unhcrthemes::theme_unhcr( font_size= 18)  +  
  theme(panel.grid.major.x  = element_line(color = "#cbcbcb"), 
        panel.grid.major.y  = element_blank(), 
        panel.grid.minor = element_blank()) + 
  labs(title = paste0("What are the main type of recorded Assistance in ", ctr, "?"),
       subtitle = paste0("There's a total of  ", scales::label_comma()(nrow(Assistance)),
                         " assistance records, ",
                         scales::label_comma(accuracy = .1)(nrow(RegistrationGroupall |>
                                                                   dplyr::filter(got_assistance== "FALSE")) / nrow(RegistrationGroupall ) *100) ,
                         " % of cases have no single associated records of assistance"),   
       x = "",
       y = "",
       caption = paste0("Source: Data available in RIDL @ ", ridl, "\n Record are counted as single occurence per type at case level.") ) 

return(p)
}

