# WARNING - Generated by {fusen} from /dev/flat_full.Rmd: do not edit by hand

#' @title Assemble all data components in a list and compute indicators
#' @description The function compute a summary chart with clusters relative description:
#' The variable modalities in each of the profiles can be __interpreted__ using the following information:  
#'   * _Cla/Mod_ is the pourcentage of records who have that modality and who are in that the profile (for instance: 50.3% of the cases who have a head of family who marrital status is single also belongs to profile 1) 
#'   * _Mod/Cla_ is the pourcentage of records in that profile who have that modality (for instance: 81.5% of the cases of profile  1 have a head of family who marrital status is single ) 
#'   * _Global_ is the global pourcentage of all records who have that modality (for instance: in all population, 51.67% of of the cases who have a head of family who marrital status is single.) 
#'   * _p-value_ provides an idea of the significant of the difference between Mod/Cla proportation & Global. If p-value is less than 0.05, then one category is significantly linked to another categories  
#'   * _v-test_ If the v-test is positive, it means that the category is over-expressed for the category and if the v-test is negative it means that the category is under-expressed for the category.What is interesting in the v-test is only the sign of the v-test. 
#'   
#'   Only variable modalities for which critical probability is below 0.02 are used."  
#'   
#' @param progres   a list with all required frame re-encoded
#' @param ctr Country or Business Unit for the dataset dump
#' @param year Year of reference
#' @param ridl  name of the project in ridl.unhcr.org, the internal UNHCR repository based on CKAN
#' @return a list with both a ggplot2 crafted chart and the summary data
#' @export 
#'
#'

#' @examples
#' 
#' #progresobj <- data_load(dataraw = system.file("demo/", package = "proGresAnalysis") )
#' # progres <- data_recode(progresobj = progresobj,  ctr = "Ecuador")
#' # plot_segment_group(progres = progres,
#' #                                     ctr = "Ecuador",
#' #                                     ridl = "data-should-be-on-ridl",
#' #                                     thisyear = 2021 ) 
plot_segment_group  <- function(progres,
                                    ctr, 
                                    ridl = "data-should-be-on-ridl",
                                    thisyear = 2021 ) { 
  
  cluster <- plot_segment_var(progres,
                                    ctr, 
                                    ridl = "data-should-be-on-ridl",
                                    thisyear = 2021 )

   data.mca.hcpc <- cluster[2]
# aggregate modalitied description of each segment
segments <- as.data.frame(data.mca.hcpc$desc.var$category$`1`) |>
  janitor::clean_names()  |>
  dplyr::mutate(mod = row.names(.))  |>
  dplyr::mutate(mod2 = gsub(".*=", "", mod)) |>
  dplyr::mutate(varcat = gsub("=.*", "", mod)) |>
  dplyr::mutate(segment = "Segment 1") |>
  rbind( as.data.frame(data.mca.hcpc$desc.var$category$`2`) |>
           janitor::clean_names()  |>
           dplyr::mutate(mod = row.names(.))  |>
           dplyr::mutate(mod2 = gsub(".*=", "", mod)) |>
           dplyr::mutate(varcat = gsub("=.*", "", mod)) |>
           dplyr::mutate(segment = "Segment 2") ) |>
  rbind( as.data.frame(data.mca.hcpc$desc.var$category$`3`) |>
           janitor::clean_names()  |>
           dplyr::mutate(mod = row.names(.))  |>
           dplyr::mutate(mod2 = gsub(".*=", "", mod)) |>
           dplyr::mutate(varcat = gsub("=.*", "", mod)) |>
           dplyr::mutate(segment = "Segment 3") ) |>
  rbind( as.data.frame(data.mca.hcpc$desc.var$category$`4`) |>
           janitor::clean_names()  |>
           dplyr::mutate(mod = row.names(.))  |>
           dplyr::mutate(mod2 = gsub(".*=", "", mod)) |>
           dplyr::mutate(varcat = gsub("=.*", "", mod)) |>
           dplyr::mutate(segment = "Segment 4") ) |>
  dplyr::mutate(mod_cla = mod_cla / 100)|>
  dplyr::mutate(cla_mod = cla_mod / 100)|>
  dplyr::mutate(global = global / 100) 

# now plotting this 
p <- ggplot(segments ) + 
  geom_col(aes(x = reorder(mod2,mod_cla), 
               y = cla_mod), fill="grey", width=0.5) + 
  geom_col(aes(x = reorder(mod2,mod_cla), 
               y = mod_cla), width=0.2) + 
  geom_errorbar(aes(x = reorder(mod2,mod_cla), 
                    y = global,
                    ymin = global,
                    ymax= global), 
                width = .45) + 
    scale_y_continuous(labels=scales::percent, breaks= seq(0, 1, by = 0.5)) +
  geom_hline(yintercept = 0, size = 1.1, colour = "#333333") +
  coord_flip() +  
  #facet_grid(varcat ~ ., scales = "free", space = "free") +
   facet_grid(. ~ segment ) +
  #facet_grid(vars(varcat), vars(segment)) +
 # facet_grid(vars(varcat) ) +
  unhcrthemes::theme_unhcr( font_size= 16)  +  
  theme(panel.grid.major.x  = element_line(color = "#cbcbcb"), 
        panel.grid.major.y  = element_blank(), 
        panel.grid.minor = element_blank(),
        strip.text.y = element_text(angle = 0),
        axis.text.x = element_text(size = 10)) + 
  labs(title = "Comparing the Characteristics of each Segments",
       subtitle =  "Modalities Distribution per Segment" ,   
       x = "",
       y = "",
       caption = paste0(str_wrap( 
         "In Black: Modality in Class  is the percentage of records in that profile who have that modality", 
         160), "\n",
         str_wrap( 
         "In Grey: Class in Modality is the percentage among all records who have that modality and who are in that the profile", 
           160), "\n",
         str_wrap( 
         "As line: Global is the global percentage of all records who have that modality ",
           160) ) ) 

return(p)


}

#' @title Assemble all data components in a list and compute indicators
#' @description The function compute a summary chart performing unsupervised classification on a series of key variables 
#'  https://www.datanovia.com/en/blog/cluster-analysis-in-r-simplified-and-enhanced/  
#'  https://www.datanovia.com/en/lessons/cluster-validation-statistics-must-know-methods/
#'  See video https://www.youtube.com/watch?v=0z30RDikYaw
#' @param progres   a list with all required frame re-encoded
#' @param ctr Country or Business Unit for the dataset dump
#' @param year Year of reference
#' @param ridl  name of the project in ridl.unhcr.org, the internal UNHCR repository based on CKAN
#' @return a list with both a ggplot2 crafted chart and the summary data
#' @export 
#'
#'

#' @examples
#' 
#' progresobj <- data_load(dataraw = system.file("demo/", package = "proGresAnalysis") )
#' progres <- data_recode(progresobj = progresobj,  ctr = "Ecuador")
#' cluster <- plot_segment_var(progres = progres,
#'                                     ctr = "Ecuador",
#'                                     ridl = "data-should-be-on-ridl",
#'                                     thisyear = 2021 )
#' 
#' cluster[[1]]
#' 
plot_segment_var  <- function(progres,
                                    ctr, 
                                    ridl = "data-should-be-on-ridl",
                                    thisyear = 2021 ) { 
  
  
     RegistrationGroupall <-  as.data.frame(progres[17]) 
     ## Step 1: Select variables used for clustering
     data2cluster <- RegistrationGroupall[,  c("group_size1", 
                  "ratio_female_cat",
                  "sex_fp",
                  "ratio_dependant_cat",
                  "age_sd_cat",  
                    "divorced_separated_widow",                         
                     "single_adult" , "single_minor" , "child_at_risk" ,
                    "married_engaged", "disability" ,
                    "specific_legal_and_physical_protection_needs",  
                    "serious_medical_condition", "sgbv" )] |>
  dplyr::mutate_if(is.integer,as.factor) |>
  dplyr::mutate_if(is.numeric,as.factor)|>
  dplyr::mutate_if(is.logical,as.factor)

samplesize <- 10000
data.sample <- data2cluster[sample(1:nrow(data2cluster), 
                            samplesize,
                            replace=FALSE), ]

## Step 2: perform Multiple correspondance analysis
data.mca <- FactoMineR::MCA(data.sample, graph= FALSE)

## Step 3: Hierarchical Classification
data.mca.hcpc <- FactoMineR::HCPC(data.mca, 
                                  nb.clust=-1, 
                                  min=3, 
                                  max=4, 
                                  graph=FALSE, 
                                  order=FALSE, 
                                  consol=TRUE, 
                                  kk=1000)

## Predict projection for new rows with Multiple Correspondence Analysis
#data.predict <- predict(data.mca, data2cluster)

## Step 4:  Associate group with clusters
cluster <- data.mca.hcpc$data.clust
cluster$clust <- as.character(cluster$clust)
cluster$clust[cluster$clust==1] <- "Segment 1"
cluster$clust[cluster$clust==2] <- "Segment 2"
cluster$clust[cluster$clust==3] <- "Segment 3"
cluster$clust[cluster$clust==4] <- "Segment 4"
cluster$clust <- as.factor(cluster$clust)

### Now create a patchwork with key plots from this 
## plot 1 with variable
pvar <- factoextra::fviz_mca_var(data.mca, 
                                 labelsize = 3, 
                                 repel = TRUE,
                                 pointsize = 0, 
                                 select.var = list(contrib = 15)) +
  labs(title = "Representation of variables proximity" )  +   
  labs(caption = "This charts display the results of Multiple Correspondance Analysis (MCA)") +
  unhcrthemes::theme_unhcr( font_size= 12)

## plot2 with cluster 
pclust <- factoextra::fviz_cluster(data.mca.hcpc,
                                   # repel = TRUE,  # Avoid label overlapping
                                   geom = "point",
                                   show.clust.cent = TRUE, # Show cluster centers
                                   palette = "jco", # Color palette see ?ggpubr::ggpar
                                   ggtheme = theme_minimal(),
                                   main = "Representation of population segment")+ 
  unhcrthemes::theme_unhcr( font_size= 12) +
  labs(caption = "This charts display the results of Hierarchical Clustering on Principal Components (HCPC)") 

## plot3 with cluster proportion
pclustprop <- ggplot(cluster, aes(x=clust)) +
  geom_bar(aes(y = ..count.. / sapply(PANEL, FUN=function(x) sum(count[PANEL == x]))),
           fill="#2a87c8",colour="#2a87c8") +
  #facet_wrap(~subgov, ncol=4) +
  guides(fill= "none") +
  ylab("Frequency") +
  scale_y_continuous(labels=scales::percent, breaks= seq(0, 1, by = 0.1)) +
  coord_flip() +
  labs( title = paste0("Share of each Population Segment in ", ctr),
       x = "", 
       y = "",
       caption = paste0("Source: Data available in RIDL @ ", ridl, "") ) + 
  unhcrthemes::theme_unhcr( font_size= 12)  +    
  theme(panel.grid.major.x  = element_line(color = "#cbcbcb"), 
        panel.grid.major.y  = element_blank(), 
        panel.grid.minor = element_blank())

## Now display the 3 charts within one single ggplot2 object with patchwork
 require(patchwork)
 p <- pvar | (pclust / pclustprop)
 
 cluster <- list( p, data.mca.hcpc)
 
 return(cluster)

}

