# WARNING - Generated by {fusen} from /dev/flat_full.Rmd: do not edit by hand

#' @title Assemble all data components in a list and compute indicators
#' @description The function compute a summary chart 
#' @param progres   a list with all required frame re-encoded
#' @param ctr Country or Business Unit for the dataset dump
#' @param year Year of reference
#' @param ridl  name of the project in ridl.unhcr.org, the internal UNHCR repository based on CKAN
#' @return a list with both a ggplot2 crafted chart and the summary data
#' @export 
#'
#'

#' @examples
#' # progresobj <- data_load(dataraw = system.file("demo/", package = "proGresAnalysis") )
#' # progres <- data_recode(progresobj = progresobj,  ctr = "Ecuador")
#' plot_incl_educ_attain(progres = progres,
#'                                     ctr = "Ecuador",
#'                                     ridl = "data-should-be-on-ridl",
#'                                     thisyear = 2021 ) 
#' 
plot_incl_educ_attain <- function(progres,
                                    ctr = "Ecuador",
                                    ridl = "data-should-be-on-ridl",
                                    thisyear = 2021 ) {   

Individual <- as.data.frame(progres[1] ) 
#levels(as.factor(Individual$EducationAttainment))
wb_data <- as.data.frame(progres[19] )

#table(Individual$EducationAttainment, useNA = "ifany")
Individual$EducationAttainment <- factor(Individual$EducationAttainment,
                                            levels = c("TER.DO","SEC.PO", 
                                                       "SEC.UP",
                                                       "SEC.LO", "PRM", "Not Measured"  ))


ed <- Individual |> 
  dplyr::filter( EducationAttainment != "Not Applicable") |> 
  dplyr::group_by(EducationAttainment ) |> 
  dplyr::summarise(n = dplyr::n()) #|>
  ## calculate cumulative 
  # dplyr::group_by(EducationAttainment ) |> 


p <- ed  |>
   dplyr::mutate(nCum =   
                dplyr::case_when(
                  EducationAttainment == "TER.DO" ~ n  ,
                  EducationAttainment == "SEC.PO" ~  
                          as.integer (ed  |> 
                                        dplyr::filter(EducationAttainment== "SEC.PO" ) |>
                                        dplyr::select(n) +
                                        ed  |> 
                                        dplyr::filter(EducationAttainment== "TER.DO" ) |>
                                        dplyr::select(n) ),  
                  EducationAttainment == "SEC.UP" ~  
                           as.integer (ed  |> 
                                       dplyr::filter(EducationAttainment== "SEC.LO" ) |>
                                       dplyr::select(n) +
                                         ed  |> 
                                         dplyr::filter(EducationAttainment== "TER.DO" ) |>
                                         dplyr::select(n) +
                                       ed  |> 
                                       dplyr::filter(EducationAttainment== "SEC.PO" ) |>
                                       dplyr::select(n) ),  
                  EducationAttainment == "SEC.LO" ~  
                          as.integer (ed  |> 
                                        dplyr::filter(EducationAttainment== "SEC.LO" ) |>
                                        dplyr::select(n) +
                                        ed  |> 
                                        dplyr::filter(EducationAttainment== "SEC.UP" ) |>
                                        dplyr::select(n) +
                                        ed  |> 
                                        dplyr::filter(EducationAttainment== "TER.DO" ) |>
                                        dplyr::select(n) +
                                        ed  |> 
                                        dplyr::filter(EducationAttainment== "SEC.PO" ) |>
                                        dplyr::select(n)  ),  
                  EducationAttainment == "PRM" ~  
                        as.integer (ed  |> 
                                      dplyr::filter(EducationAttainment== "SEC.LO" ) |>
                                      dplyr::select(n) +
                                      ed  |> 
                                      dplyr::filter(EducationAttainment== "PRM" ) |>
                                      dplyr::select(n) +
                                      ed  |> 
                                      dplyr::filter(EducationAttainment== "SEC.UP" ) |>
                                      dplyr::select(n) +
                                      ed  |> 
                                      dplyr::filter(EducationAttainment== "TER.DO" ) |>
                                      dplyr::select(n) +
                                      ed  |> 
                                      dplyr::filter(EducationAttainment== "SEC.PO" ) |>
                                      dplyr::select(n)   )
                  )) |>
  dplyr::mutate(valueR = round(nCum / sum(n) *100, 3)) |> 
    dplyr::mutate( #source = "UNHCR Primes",
                  dateR =  2021 ) |>
  dplyr::mutate(indicator_id = dplyr::case_when(
    EducationAttainment == "PRM" ~ "SE.PRM.CUAT.ZS",
    EducationAttainment == "SEC.LO" ~ "SE.SEC.CUAT.LO.ZS",        
    EducationAttainment == "SEC.UP" ~ "SE.SEC.CUAT.UP.ZS",
    EducationAttainment == "SEC.PO" ~ "SE.SEC.CUAT.PO.ZS",          
    EducationAttainment == "TER.DO" ~ "SE.TER.CUAT.DO.ZS")) |> 
  dplyr::filter( indicator_id %in% wb_data$indicator_id) |>
  dplyr::select( indicator_id,dateR,  valueR ) |>
  #dplyr::arrange(desc(value)) |>
  dplyr::left_join(wb_data) |>
  dplyr::mutate(indicator  = dplyr::case_when(
    indicator_id == "SE.PRM.CUAT.ZS"  ~ "At least completed primary", ## PRM + LO +UP + PO +DO
    indicator_id ==  "SE.SEC.CUAT.LO.ZS"~ "At least completed lower secondary (grade 6-9)", ## LO + UP + PO +DO      
    indicator_id ==  "SE.SEC.CUAT.UP.ZS"~ "At least completed upper secondary (grade 10-14)", ##  UP + PO +DO
    indicator_id ==  "SE.SEC.CUAT.PO.ZS"~ "At least completed post-secondary",  ## PO +DO         
    indicator_id ==  "SE.TER.CUAT.DO.ZS"~ "Doctoral or equivalent" )) |>  # DO
  dplyr::mutate(indicator  = factor(indicator,
                        levels = c("At least completed primary",
                                   "At least completed lower secondary (grade 6-9)",
                                   "At least completed upper secondary (grade 10-14)",
                                   "At least completed post-secondary",
                                   "Doctoral or equivalent"))) |> 
  dplyr::filter( !(is.na(indicator)) )  |> 
  ggplot( ) + 
  geom_bar(aes(x = indicator, 
               y = value),
           fill = "gray80",
           stat = "identity") + 
  geom_bar(aes(x = indicator, 
               y = valueR),
           fill = "#0072bc", 
           width = .6,
           stat = "identity") + 
  coord_flip() + 
  scale_y_continuous( label = scales::label_number_si() ) + 
  geom_hline(yintercept = 0, size = 1.1, colour = "#333333") +
  unhcrthemes::theme_unhcr( font_size= 18)  +  
  theme(panel.grid.major.x  = element_line(color = "#cbcbcb"), 
        panel.grid.major.y  = element_blank(), 
        panel.grid.minor = element_blank()) + 
  labs(title = "How Education Attainment  of registered Population (blue) compare with Host?",
       subtitle = paste0("Attainement relates to the cumulative percentage of population ages 25 and over that attained certain levels in ",ctr),   
       x = "",
       y = "",
       caption = paste0("Source: Data available in RIDL @ ", ridl, " compared with baseline information for the country from UNESCO Institute for Statistics\n", str_wrap( 
         "A relative high concentration of the adult population in a given level of education reflects the capacity of the educational system in the corresponding level of education. Educational attainment is closely related to the skills and competencies of a country's population, and could be seen as a proxy of both the quantitative and qualitative aspects of the stock of human capital (see International Standard Classification of Education - ISCED).", 
         180)) ) 

return(p)
}


#' @title Assemble all data components in a list and compute indicators
#' @description The function compute a summary chart 
#'   * "SE.PRE.ENRR", # School enrollment, preprimary -Age 3-5 (% gross) -
#'   * "SE.PRM.ENRR", # School enrollment, primary -Age 6 -11(% gross)  
#'   * "SE.SEC.ENRR", # School enrollment, secondary -Age 12-19 (% gross)
#'   * "SE.TER.ENRR" # School enrollment, tertiary -Age 20-24  (% gross) 
#' @param progres   a list with all required frame re-encoded
#' @param ctr Country or Business Unit for the dataset dump
#' @param year Year of reference
#' @param ridl  name of the project in ridl.unhcr.org, the internal UNHCR repository based on CKAN
#' @return a list with both a ggplot2 crafted chart and the summary data
#' @export 
#'
#'

#' @examples
#' # progresobj <- data_load(dataraw = system.file("demo/", package = "proGresAnalysis") )
#' # progres <- data_recode(progresobj = progresobj,  ctr = "Ecuador")
#' plot_incl_educ_enroll (progres = progres,
#'                                     ctr = "Ecuador" ,
#'                                     ridl = "data-should-be-on-ridl",
#'                                     thisyear = 2021 )
#' 
plot_incl_educ_enroll <- function(progres,
                                    ctr, 
                                    ridl = "data-should-be-on-ridl",
                                    thisyear = 2021 ) {  
  
#levels(as.factor(Individual$EducationEnroll))
# "SE.PRE.ENRR", # School enrollment, preprimary -Age 3-5 (% gross) -
# "SE.PRM.ENRR", # School enrollment, primary -Age 6 -11(% gross)  
# "SE.SEC.ENRR", # School enrollment, secondary -Age 12-19 (% gross)
# "SE.TER.ENRR" # School enrollment, tertiary -Age 20-24  (% gross) 
  

Individual <- as.data.frame(progres[1] ) 
wb_data <- as.data.frame(progres[19] )

#wb_data$indicator_id

edEnroll <- Individual |> 
  dplyr::filter(!(is.na(Individual$EducationEnrollShould))) |> 
  dplyr::group_by(EducationEnroll  ) |> 
  dplyr::summarise(n = dplyr::n() ) |> 
  dplyr::filter(!(is.na( EducationEnroll)))  

#levels(as.factor(edEnroll$EducationEnroll))

ed <- Individual |> 
  dplyr::filter(!(is.na(Individual$EducationEnrollShould))) |> 
  
  dplyr::group_by(EducationEnrollShould ) |> 
  dplyr::summarise(n = dplyr::n(),
                   enrollatRightAge =  sum(EducationEnrollatRightAge == "yes"),
                   enrollNet = enrollatRightAge /n *100 ) |>
  
  dplyr::mutate( nEnrollCurrent = dplyr::case_when(
    EducationEnrollShould == "should.be.in.preprimary" ~ 
         as.integer(edEnroll[edEnroll$EducationEnroll=="is.in.preprimary", c("n")]),
    EducationEnrollShould == "should.be.in.primary" ~ 
      as.integer(edEnroll[edEnroll$EducationEnroll=="is.in.primary", c("n")]),       
    EducationEnrollShould == "should.be.in.secondary"  ~ 
      as.integer(edEnroll[edEnroll$EducationEnroll=="is.in.secondary", c("n")]),
    EducationEnrollShould == "should.be.in.tertiary"  ~ 
      as.integer(edEnroll[edEnroll$EducationEnroll=="is.in.tertiary", c("n")]) )) |> 
  dplyr::mutate(valueR = nEnrollCurrent /n *100 )  



dat <- ed |> 
  dplyr::mutate( #source = "UNHCR Primes",
    dateR =  2021 ) |>
  dplyr::mutate(indicator_id = dplyr::case_when(
    EducationEnrollShould == "should.be.in.preprimary" ~ "SE.PRE.ENRR",
    EducationEnrollShould == "should.be.in.primary" ~ "SE.PRM.ENRR",        
    EducationEnrollShould == "should.be.in.secondary" ~ "SE.SEC.ENRR",
    EducationEnrollShould == "should.be.in.tertiary" ~ "SE.TER.ENRR")) |> 
  dplyr::filter( indicator_id %in% wb_data$indicator_id) |>
  dplyr::select( indicator_id,dateR,  valueR ) |>
  #dplyr::arrange(desc(value)) |>
  dplyr::left_join(wb_data) |>
  dplyr::mutate(indicator  = dplyr::case_when(
    indicator_id == "SE.PRE.ENRR"  ~ "School enrollment, preprimary -Age 3-5", 
    indicator_id ==  "SE.PRM.ENRR"~ "School enrollment, primary -Age 6 -11",      
    indicator_id ==  "SE.SEC.ENRR"~ "School enrollment, secondary -Age 12-19", 
    indicator_id ==  "SE.TER.ENRR"~ "School enrollment, tertiary -Age 20-24")) |>  
  dplyr::mutate(indicator  = factor(indicator,
                                    levels = c("School enrollment, preprimary -Age 3-5",
                                               "School enrollment, primary -Age 6 -11",
                                               "School enrollment, secondary -Age 12-19",
                                               "School enrollment, tertiary -Age 20-24"))) |> 
  dplyr::filter( !(is.na(indicator)) )  

p <- dat |> 
  ggplot( ) + 
  geom_bar(aes(x = indicator, 
               y = value),
           fill = "gray80",
           stat = "identity") + 
  geom_bar(aes(x = indicator, 
               y = valueR),
           fill = "#0072bc", 
           width = .6,
           stat = "identity") + 
  coord_flip() + 
  scale_y_continuous( label = scales::label_number_si(),
                      breaks= seq(0, 100, by = 20)) +
  geom_hline(yintercept = 0, size = 1.1, colour = "#333333") +
  unhcrthemes::theme_unhcr( font_size= 18)  +  
  theme(panel.grid.major.x  = element_line(color = "#cbcbcb"), 
        panel.grid.major.y  = element_blank(), 
        panel.grid.minor = element_blank()) + 
  labs(title = "How Education Enrollment of registered Population (blue) compare with Host?",
       subtitle = paste0("Percentage of kids enrolled at certain level vis a vis all kids that should in that level in ", ctr),   
       x = "",
       y = "As % (this can be more than 100%, as there might be more enrollment in a level than what the regular age group would imply)",
       caption = paste0( "Source: Data available in RIDL @ ",
                         ridl, 
                         " compared with baseline information for the country from UNESCO Institute for Statistics\n",
                        str_wrap( 
         "Note that UNHCR captures school attendance at time of registration, which is slightly different from the concept of Enrollment. Gross enrollment ratios indicate the capacity of each level of the education system, but a high ratio may reflect a substantial number of overage children enrolled in each grade because of repetition or late entry rather than a successful education system. The net enrollment rate excludes overage and underage students and more accurately captures the system's coverage and internal efficiency. Differences between the gross enrollment ratio and the net enrollment rate show the incidence of overage and underage enrollments  (see International Standard Classification of Education - ISCED). ", 
                         180)) ) 

return(p)
}


#' @title Assemble all data components in a list and compute indicators
#' @description The function compute a summary chart . Build with isco http://www.harryganzeboom.nl/isco08/qa-isco-08.htm
#' @param progres   a list with all required frame re-encoded
#' @param ctr Country or Business Unit for the dataset dump
#' @param year Year of reference
#' @param ridl  name of the project in ridl.unhcr.org, the internal UNHCR repository based on CKAN
#' @return a list with both a ggplot2 crafted chart and the summary data
#' @export 
#'
#'

#' @examples
#' 
#' # progresobj <- data_load(dataraw = system.file("demo/", package = "proGresAnalysis") )
#' # progres <- data_recode(progresobj = progresobj,  ctr = "Ecuador")
#' plot_incl_occup(progres = progres ,
#'                                     ctr = "Ecuador",
#'                                     ridl = "data-should-be-on-ridl",
#'                                     thisyear = 2021 ) 
#' 
plot_incl_occup  <- function(progres,
                                    ctr = "Ecuador",
                                    ridl = "data-should-be-on-ridl",
                                    thisyear = 2021 ) { 
 Individual <- as.data.frame(progres[1] ) 

 p <- Individual |> 
  # dplyr::left_join(WorkExperience |>
  #                    dplyr::mutate(WorkExperience = WorkType) |>
  #                    dplyr::mutate(ModifiedOnWork = ModifiedOn) |>
  #                    dplyr::select(IndividualID, WorkExperience,ModifiedOnWork) ,
  #                  by = c("IndividualID")) |> 
  # dplyr::arrange(desc(ModifiedOnWork)) |> 
  # dplyr::filter(!duplicated(IndividualID, fromLast = FALSE)) |> 
  dplyr::group_by( WorkExperience  ) |> 
  dplyr::summarise(n = dplyr::n()) |> 
  mutate(n = as.numeric(n), 
         nRound =  ifelse(n > 1000, 
                          paste(scales::label_number_si(accuracy = 0.1)(n)),
                          as.character(n) ) ) |>
 dplyr::filter( ! (is.na(WorkExperience) )) |> 
  arrange(desc(n)) |>
  head(15) |> 
  ggplot( aes(x = reorder(WorkExperience, n),
              y = n )) + 
  geom_bar(stat = "identity", 
           fill = "#0072bc") + 
  coord_flip() + 
  scale_y_continuous( label = scales::label_number_si() ) + 
    ## Position label differently in the bar in white - outside bar in black
    geom_label( data =   function(x) subset(x, n < max(n) / 1.5),
                aes(x = reorder(WorkExperience, n),
                y = n,
                    label= nRound),
                hjust = -0.1 ,
                vjust = 0.5, 
                colour = "black", 
                fill = NA, 
                label.size = NA, 
                family = "Lato", 
                size = 4   ) +  
  
    geom_label( data =   function(x) subset(x, n >= max(n) / 1.5),
                aes(x = reorder(WorkExperience, n),
                y = n,
                    label= nRound),
                hjust = 1.1 ,
                vjust = 0.5, 
                colour = "white", 
                fill = NA, 
                label.size = NA, 
                family = "Lato", 
                size = 4   ) +   
  geom_hline(yintercept = 0, size = 1.1, colour = "#333333") +
  unhcrthemes::theme_unhcr( font_size= 18)  +  
  theme(panel.grid.major.x  = element_line(color = "#cbcbcb"), 
        panel.grid.major.y  = element_blank(), 
        panel.grid.minor = element_blank()) + 
  labs(title = "What are the main type of work before asylum declared by registered individual?",
       subtitle = paste0("Among the ", scales::label_comma()(nrow(Individual)),
                         " records, ",
                         scales::label_comma()(nrow(Individual |>dplyr::filter( !(is.na(WorkExperience) )))),
                         " includes information on this topic in ", ctr),   
       x = "",
       y = "",
       caption = paste0("Source: Data available in RIDL @ ", ridl) ) 

return(p)

  }

#' @title Assemble all data components in a list and compute indicators
#' @description The function compute a summary chart 
#' @param progres   a list with all required frame re-encoded
#' @param ctr Country or Business Unit for the dataset dump
#' @param year Year of reference
#' @param ridl  name of the project in ridl.unhcr.org, the internal UNHCR repository based on CKAN
#' @return a list with both a ggplot2 crafted chart and the summary data
#' @export 
#'
#'

#' @examples
#' 
#' # progresobj <- data_load(dataraw = system.file("demo/", package = "proGresAnalysis") )
#' # progres <- data_recode(progresobj = progresobj,  ctr = "Ecuador")
#' plot_incl_work(progres = progres,
#'                                     ctr = "Ecuador",
#'                                     ridl = "data-should-be-on-ridl",
#'                                     thisyear = 2021 )
#' 
plot_incl_work  <- function(progres,
                                    ctr = "Ecuador",
                                    ridl = "data-should-be-on-ridl",
                                    thisyear = 2021 ) { 
#
# names(WorkExperience)
# WorkExperience |> 
#   dplyr::group_by( WorkType, CountryOfWork   ) |> 
#   dplyr::summarise(n = dplyr::n()) |> 
#   mutate(n = as.numeric(n), 
#          nRound =  ifelse(n > 1000, 
#                            paste(scales::label_number_si(accuracy = 0.1)(n)),
#                            as.character(n) ) ) |>
#  dplyr::filter( ! (is.na(WorkType) )) |> 
#  dplyr::filter( CountryOfWork != ctr ) |> 
#   arrange(desc(n)) |>
#   head(10)  |> 
#   ggplot( aes(x = reorder(WorkType, n),
#               y = n )) + 
#   geom_bar(stat = "identity", 
#            fill = "#0072bc") + 
#   coord_flip() + 
#   scale_y_continuous( label = scales::label_number_si() ) + 
#     ## Position label differently in the bar in white - outside bar in black
#     geom_label( data =   function(x) subset(x, n < max(n) / 1.5),
#                 aes(x = reorder(WorkType, n),
#                 y = n,
#                     label= nRound),
#                 hjust = -0.1 ,
#                 vjust = 0.5, 
#                 colour = "black", 
#                 fill = NA, 
#                 label.size = NA, 
#                 family = "Lato", 
#                 size = 4   ) +  
#   
#     geom_label( data =   function(x) subset(x, n >= max(n) / 1.5),
#                 aes(x = reorder(WorkType, n),
#                 y = n,
#                     label= nRound),
#                 hjust = 1.1 ,
#                 vjust = 0.5, 
#                 colour = "white", 
#                 fill = NA, 
#                 label.size = NA, 
#                 family = "Lato", 
#                 size = 4   ) +    
#   scale_x_discrete(labels = function(x) {x |> str_wrap(40)}) +
#   geom_hline(yintercept = 0, size = 1.1, colour = "#333333") +
#   unhcrthemes::theme_unhcr( font_size= 18)  +  
#   theme(panel.grid.major.x  = element_line(color = "#cbcbcb"), 
#         panel.grid.major.y  = element_blank(), 
#         panel.grid.minor = element_blank()) + 
#   labs(title = paste0("Top 10 Work Experience Type outside ", ctr),
#        subtitle = paste0("Among the ", scales::label_comma()(nrow(WorkExperience)),
#                          " records, ",
#                          scales::label_comma()(nrow(WorkExperience |>dplyr::filter( !(is.na(WorkType) )))),
#                          " includes information on this topic"),   
#        x = "",
#        y = "",
#        caption = paste0("Source: Data available in RIDL @ ", ridl) )
}

