# WARNING - Generated by {fusen} from /dev/flat_full.Rmd: do not edit by hand

#' @title Assemble all data components in a list and compute indicators
#' @description The function compute a summary chart 
#' @param progres   a list with all required frame re-encoded
#' @param ctr Country or Business Unit for the dataset dump
#' @param year Year of reference
#' @param ridl  name of the project in ridl.unhcr.org, the internal UNHCR repository based on CKAN
#' @return a list with both a ggplot2 crafted chart and the summary data
#' @export 
#'
#'

#' @examples
#' 
#' # progresobj <- data_load(dataraw = system.file("demo/", package = "proGresAnalysis") )
#' # progres <- data_recode(progresobj = progresobj,  ctr = "Ecuador")
#' plot_prot_doc (progres = progres,
#'                                     ctr = "Ecuador",
#'                                     ridl = "data-should-be-on-ridl",
#'                                     thisyear = 2021 )
plot_prot_doc  <- function(progres,
                                    ctr = "Ecuador",
                                    ridl = "data-should-be-on-ridl",
                                    thisyear = 2021 ) { 
#names(Document)
#levels(as.factor(Document$DocumentType))


Individual <- as.data.frame(progres[1] ) 
Document <-  as.data.frame(progres[4] )

p <- Individual |> 
  dplyr::filter( LegalStatus != "Not of concern" ) |> 
  #names(Individual)
  dplyr::select(IndividualID, Age, AgeCohort, Sex, LegalStatus ) |> 
  dplyr::left_join(Document) |> 
  
  ## Add something for individuals that have no linked doc
  dplyr::mutate( DocumentType = dplyr::if_else(is.na(DocumentType), "No records of Document", DocumentType)) |> 
  ## Clean record with "-"
  dplyr::mutate( DocumentType = dplyr::if_else(DocumentType== "-", "Unknown (no event)" , DocumentType)) |> 
  ## Clean Document type
  dplyr::mutate(DocumentType = str_replace(DocumentType, " \\(no event\\)", ""))  |> 
  ## Concat document type and status
  dplyr::mutate( doctypestatus = paste0( DocumentType,
                                         dplyr::if_else(is.na(DocumentStatus), " ", 
                                                        paste0(" / ",  DocumentStatus) ))) |> 
  ## clean potential duplicate
  dplyr::distinct(IndividualID, doctypestatus, .keep_all = TRUE)  |>   
  
  dplyr::group_by( doctypestatus  ) |> 
  dplyr::summarise(cnt = dplyr::n())    |> 
  dplyr::mutate( totalind = nrow(Individual |> 
                                   dplyr::filter( LegalStatus != "Not of concern" )),
                 n = cnt/totalind  )    |>  # 
  dplyr::mutate(n = as.numeric(n), 
         nRound =  paste0( scales::label_number_si(accuracy = 0.1)(n*100),  "%"))    |>
  dplyr::mutate(flag = dplyr::if_else(doctypestatus == "No records of Document ", "yes",   "no" ))    |>
  #dplyr::filter( ! (is.na(doctypestatus) )) |> 
  arrange(desc(n)) |>
  head(15)    |> 
  ggplot( aes(x = reorder(doctypestatus,n), 
              y = n,
              fill = flag)) + 
  guides(fill= "none") +
  scale_colour_manual(values = c("#0072bc", "#CCCCCC"),
                      aesthetics = c("colour", "fill")) +
  geom_bar(stat = "identity" ) + 
          # fill = "#0072bc") + 
  coord_flip() + 
  scale_y_continuous(labels=scales::percent, breaks= seq(0, 1, by = 0.2)) +
  ## Position label differently in the bar in white - outside bar in black
  geom_label( data =   function(x) subset(x, n < max(n) / 1.5),
              aes(x = reorder(doctypestatus, n),
                  y = n,
                  label= nRound),
              hjust = -0.1 ,
              vjust = 0.5, 
              colour = "black", 
              fill = NA, 
              label.size = NA, 
              family = "Lato", 
              size = 4   ) +  
  
  geom_label( data =   function(x) subset(x, n >= max(n) / 1.5),
              aes(x = reorder(doctypestatus, n),
                  y = n,
                  label= nRound),
              hjust = 1.1 ,
              vjust = 0.5, 
              colour = "white", 
              fill = NA, 
              label.size = NA, 
              family = "Lato", 
              size = 4   ) +   
  geom_hline(yintercept = 0, size = 1.1, colour = "#333333") +
  unhcrthemes::theme_unhcr( font_size= 18)  +  
  theme(panel.grid.major.x  = element_line(color = "#cbcbcb"), 
        panel.grid.major.y  = element_blank(), 
        panel.grid.minor = element_blank()) + 
  labs(title = "What type of documentation registered individuals have? ",
       subtitle = paste0("Top 15 Documentation type & status in ",ctr),   
       x = "",
       y = "",
       caption = paste0("Source: Data available in RIDL @ ", ridl, "\n One individual can actually have more than one type of document, except when there is No records of Document") )

 return(p)
  
  ## Add annotation -- use ggannotate to get the right  coordinate within chart
  #remotes::install_github("mattcowgill/ggannotate")
  #ggannotate::ggannotate()
  
  # geom_curve(aes(xend = 10.9476141263782, yend = 2959.93589579213, 
  #                x = 6.91965137456717, y = 28668.752697603),
  #            size = 2, color = "tan",
  #            arrow = arrow(length = unit(0.07, "npc"))) +
  # ggtext::geom_textbox(data = data.frame(x = 6.91965137456717, y = 28668.752697603, 
  #                                        label = "Why so many people are using **other** category? \n Is there an important missing category within Primes?"),
  #                     mapping = aes(x = x, y = y, label = label),
  #                     width = unit(0.6, "npc"),
  #                     family = "Lato", size = 7, fill = "cornsilk",
  #                     inherit.aes = FALSE)
}


#' @title Assemble all data components in a list and compute indicators
#' @description The function compute a summary chart 
#' @param progres   a list with all required frame re-encoded
#' @param ctr Country or Business Unit for the dataset dump
#' @param year Year of reference
#' @param ridl  name of the project in ridl.unhcr.org, the internal UNHCR repository based on CKAN
#' @return a list with both a ggplot2 crafted chart and the summary data
#' @export 
#'
#'

#' @examples
#' 
#' # progresobj <- data_load(dataraw = system.file("demo/", package = "proGresAnalysis") )
#' # progres <- data_recode(progresobj = progresobj,  ctr = "Ecuador")
#' 
#' plot_prot_ratio (progres = progres,
#'                                     ctr = "Ecuador",
#'                                     ridl = "data-should-be-on-ridl",
#'                                     thisyear = 2021 )
#' 
plot_prot_ratio  <- function(progres,
                                    ctr ,
                                    ridl = "data-should-be-on-ridl",
                                    thisyear = 2021 ) { 
  
  RegistrationGroupall <-  as.data.frame(progres[17]) 
  
pfemaleRat <- RegistrationGroupall |> 
  dplyr::group_by( ratio_female_cat  ) |> 
  dplyr::summarise(n = dplyr::n()) |> 
  mutate(n = as.numeric(n), 
         nRound =  ifelse(n > 1000, 
                          paste(scales::label_number_si(accuracy = 0.1)(n)),
                          as.character(n) ) ) |>
 dplyr::filter( ! (is.na(ratio_female_cat) )) |> 
  arrange(desc(n)) |>
  head(15)  |> 
 ggplot( aes(x = ratio_female_cat, 
            y = n )) + 
  geom_bar(stat = "identity", 
           fill = "#0072bc") + 
  coord_flip() + 
  scale_y_continuous( label = scales::label_number_si() ) + 
  ## Position label differently in the bar in white - outside bar in black
  geom_label( data =   function(x) subset(x, n < max(n) / 1.5),
              aes(x = ratio_female_cat,
                  y = n,
                  label= nRound),
              hjust = -0.1 ,
              vjust = 0.5, 
              colour = "black", 
              fill = NA, 
              label.size = NA, 
              family = "Lato", 
              size = 4   ) +  
  
  geom_label( data =   function(x) subset(x, n >= max(n) / 1.5),
              aes(x = ratio_female_cat,
                  y = n,
                  label= nRound),
              hjust = 1.1 ,
              vjust = 0.5, 
              colour = "white", 
              fill = NA, 
              label.size = NA, 
              family = "Lato", 
              size = 4   ) +   
  geom_hline(yintercept = 0, size = 1.1, colour = "#333333") +
  unhcrthemes::theme_unhcr( font_size= 18)  +  
  theme(panel.grid.major.x  = element_line(color = "#cbcbcb"), 
        panel.grid.major.y  = element_blank(), 
        panel.grid.minor = element_blank()) + 
  labs(title = " ",
       subtitle = paste0("Proportion of Female "),   
       x = "",
       y = "" ) 

pyouthRat <- RegistrationGroupall |> 
  dplyr::group_by( ratio_youth_cat  ) |> 
  dplyr::summarise(n = dplyr::n()) |> 
  mutate(n = as.numeric(n), 
         nRound =  ifelse(n > 1000, 
                          paste(scales::label_number_si(accuracy = 0.1)(n)),
                          as.character(n) ) ) |>
 dplyr::filter( ! (is.na(ratio_youth_cat) )) |> 
  arrange(desc(n)) |>
  head(15)  |> 
  ggplot( aes(x = ratio_youth_cat, 
              y = n )) + 
  geom_bar(stat = "identity", 
           fill = "#0072bc") + 
  coord_flip() + 
  scale_y_continuous( label = scales::label_number_si() ) + 
  ## Position label differently in the bar in white - outside bar in black
  geom_label( data =   function(x) subset(x, n < max(n) / 1.5),
              aes(x = ratio_youth_cat,
                  y = n,
                  label= nRound),
              hjust = -0.1 ,
              vjust = 0.5, 
              colour = "black", 
              fill = NA, 
              label.size = NA, 
              family = "Lato", 
              size = 4   ) +  
  
  geom_label( data =   function(x) subset(x, n >= max(n) / 1.5),
              aes(x = ratio_youth_cat,
                  y = n,
                  label= nRound),
              hjust = 1.1 ,
              vjust = 0.5, 
              colour = "white", 
              fill = NA, 
              label.size = NA, 
              family = "Lato", 
              size = 4   ) +   
  geom_hline(yintercept = 0, size = 1.1, colour = "#333333") +
  unhcrthemes::theme_unhcr( font_size= 18)  +  
  theme(panel.grid.major.x  = element_line(color = "#cbcbcb"), 
        panel.grid.major.y  = element_blank(), 
        panel.grid.minor = element_blank()) + 
  labs(title = " ",
       subtitle = paste0("Youth Dependency"),   
       x = "",
       y = "" ) 


peldernRat <- RegistrationGroupall |> 
  dplyr::group_by( ratio_eldern_cat  ) |> 
  dplyr::summarise(n = dplyr::n()) |> 
  mutate(n = as.numeric(n), 
         nRound =  ifelse(n > 1000, 
                          paste(scales::label_number_si(accuracy = 0.1)(n)),
                          as.character(n) ) ) |>
 dplyr::filter( ! (is.na(ratio_eldern_cat) )) |> 
  arrange(desc(n)) |>
  head(15)  |> 
  ggplot( aes(x = ratio_eldern_cat, 
              y = n )) + 
  geom_bar(stat = "identity", 
           fill = "#0072bc") + 
  coord_flip() + 
  scale_y_continuous( label = scales::label_number_si() ) + 
  ## Position label differently in the bar in white - outside bar in black
  geom_label( data =   function(x) subset(x, n < max(n) / 1.5),
              aes(x = ratio_eldern_cat,
                  y = n,
                  label= nRound),
              hjust = -0.1 ,
              vjust = 0.5, 
              colour = "black", 
              fill = NA, 
              label.size = NA, 
              family = "Lato", 
              size = 4   ) +  
  
  geom_label( data =   function(x) subset(x, n >= max(n) / 1.5),
              aes(x = ratio_eldern_cat,
                  y = n,
                  label= nRound),
              hjust = 1.1 ,
              vjust = 0.5, 
              colour = "white", 
              fill = NA, 
              label.size = NA, 
              family = "Lato", 
              size = 4   ) +   
  geom_hline(yintercept = 0, size = 1.1, colour = "#333333") +
  unhcrthemes::theme_unhcr( font_size= 18)  +  
  theme(panel.grid.major.x  = element_line(color = "#cbcbcb"), 
        panel.grid.major.y  = element_blank(), 
        panel.grid.minor = element_blank()) + 
  labs(title = " ",
       subtitle = paste0("Eldern Dependency"),   
       x = "",
       y = "" ) 


require(patchwork)
p <- pfemaleRat  + 
        pyouthRat +  
        peldernRat  + 
        plot_annotation(
              title = paste0("What are the Case composition Ratio within each Registered Group in ", ctr, "?"),
              caption = paste0("Source: Data available in RIDL @ ", ridl, "\n. This information can provide an initial overview of potential vulnerabilities within the case load.") )
              
return(p)

}

#' @title Assemble all data components in a list and compute indicators
#' @description The function compute a summary chart 
#' @param progres   a list with all required frame re-encoded
#' @param ctr Country or Business Unit for the dataset dump
#' @param year Year of reference
#' @param ridl  name of the project in ridl.unhcr.org, the internal UNHCR repository based on CKAN
#' @return a list with both a ggplot2 crafted chart and the summary data
#' @export 
#'
#'

#' @examples
#' 
#' # progresobj <- data_load(dataraw = system.file("demo/", package = "proGresAnalysis") )
#' # progres <- data_recode(progresobj = progresobj,  ctr = "Ecuador")
#' 
#' plot_prot_spneedass (progres = progres,
#'                                     ctr = "Ecuador",
#'                                     ridl = "data-should-be-on-ridl",
#'                                     thisyear = 2021 )
#' 
plot_prot_spneedass  <- function(progres,
                                    ctr  ,
                                    ridl = "data-should-be-on-ridl",
                                    thisyear = 2021 ) { 
Individual <- as.data.frame(progres[1] ) 
SpecificNeed <-  as.data.frame(progres[14] )
  
topneeds <- as.vector(as.data.frame(SpecificNeed |> 
  dplyr::left_join( y = Individual,
                    by = c("IndividualID")) |> 
  dplyr::group_by( RegistrationGroupID, SpecificNeedSub   ) |> 
  dplyr::summarise(n = dplyr::n()) |> 
 dplyr::filter( ! (is.na(SpecificNeedSub) ))  |> 
 dplyr::filter( ! (is.na(RegistrationGroupID) ))   |> 
  dplyr::group_by( SpecificNeedSub  ) |> 
  dplyr::summarise(uniquecase = dplyr::n())  |>    
  dplyr::arrange(desc(uniquecase)) |>
  head(15) |>
  dplyr::select(SpecificNeedSub)   ))  |>
  as.data.frame() |>
  dplyr::pull()

 
d1 <- SpecificNeed |> 
  dplyr::filter(SpecificNeedSub  %in%  topneeds ) |>
  dplyr::left_join( y = Individual,
                    by = c("IndividualID")) |> 
  dplyr::group_by( RegistrationGroupID, SpecificNeedSub   ) |> 
  dplyr::summarise(n = dplyr::n())  |> 
 dplyr::filter( ! (is.na(RegistrationGroupID) ))  |>
  tidyr::pivot_wider(names_from  = SpecificNeedSub,
                     values_from = n) #|> 
d <- d1  |> 
  dplyr::mutate( dplyr::across(where(is.integer), ~ tidyr::replace_na(.x, 0)) )# |>
 #replace(is.na(.), 0)
 # mutate(  across(everything(), ~replace_na(.x, 0))  )

# d  |>
#   dplyr::ungroup() |>
#   dplyr::select( - 1 ) |> 
#   corrr::correlate() |> 
#   corrr::network_plot(min_cor = 0.3)

d2 <- d  |>
  dplyr::ungroup() |>
  dplyr::select( - 1 )  

# Create a tidy data frame of correlations
corr <- d2 |> 
  corrr::correlate() 

corrMat <- round(cor(d2), 1)
p.mat <- ggcorrplot::cor_pmat(d2)
#corrr::correlate(d2) 

p <- ggcorrplot::ggcorrplot(  corrMat  ,
           hc.order = TRUE,
           type = "lower",
            method = "circle",
           outline.col = "white",
           ggtheme = ggplot2::theme_gray,
           colors = c("#6D9EC1", "white", "#E46726") ,
           ## cross if not significant
            p.mat = p.mat) + 
   guides(fill= "none") +
  unhcrthemes::theme_unhcr( font_size= 12)  +  
   theme(axis.text.x = element_text(size = 8, angle = 40,  hjust=1),
        axis.text.y = element_text(size = 8) ) +
  labs(
    y = "",
    x = " ",
    title = paste0("What are the main Associations between different types of Specific needs in ", ctr, "?"),
    subtitle = str_wrap( 
      "Correlation analysis: Red color indicate a positive association, while blue a negative one. The bigger the dot, the stronger the association, cross indicates the absence of significative association",
      180) ,
    caption = paste0("Source: Data available in RIDL @ ", ridl, "")
  )
return(p)

# tidy_cors <-corr |> 
#   corrr::stretch()
# 
# 
# # Convert correlations stronger than some value
# # to an undirected graph object
# graph_cors <- tidy_cors |>
#  dplyr::filter(abs(r) > .1) |>
#   igraph::graph_from_data_frame(directed = FALSE)
# 
# # Plot
# ggraph(graph_cors) +
#   geom_edge_link(aes(edge_alpha = abs(r),
#                      edge_width = abs(r), 
#                      color = r)) +
#   guides(edge_alpha = "none", 
#          edge_width = "none") +
#   scale_edge_colour_gradientn(limits = c(-1, 1), 
#                               # colors = c("firebrick2",
#                               #            "dodgerblue2")
#                               colors = c("blue", "gray90",  "red")
#                               ) +
#   geom_node_point(color = "gray90", 
#                   size = 7) +
#   geom_node_text(aes(label = name), 
#                  repel = TRUE) + 
#   unhcrthemes::theme_unhcr( font_size= 18)  +  
#   theme(panel.grid.major.x  = element_blank(), 
#         panel.grid.major.y  = element_blank(), 
#         panel.grid.minor = element_blank(), 
#         axis.text.x =  element_blank(), 
#         axis.text.y = element_blank(), 
#         legend.key.height= unit(0.5, 'cm'),
#         legend.key.width= unit(3, 'cm') ) +
#   labs(
#     y = "",
#     x = " ",
#     title = paste0("What are the main Association between different types of Specific needs in ", ctr, "?"),
#     subtitle = paste0("Correlation analysis: Red color indicate a positive association, while blue a negative one. "),
#     caption = paste0("Source: Data available in RIDL @ ", ridl, "")
#   )
}

#' @title Assemble all data components in a list and compute indicators
#' @description The function compute a summary chart 
#' @param progres   a list with all required frame re-encoded
#' @param ctr Country or Business Unit for the dataset dump
#' @param year Year of reference
#' @param ridl  name of the project in ridl.unhcr.org, the internal UNHCR repository based on CKAN
#' @return a list with both a ggplot2 crafted chart and the summary data
#' @export 
#'

#' @examples
#' 
#' # progresobj <- data_load(dataraw = system.file("demo/", package = "proGresAnalysis") )
#' # progres <- data_recode(progresobj = progresobj,  ctr = "Ecuador")
#' plot_prot_spneedcat  (progres = progres,
#'                                     ctr = "Ecuador",
#'                                     ridl = "data-should-be-on-ridl",
#'                                     thisyear = 2021 )
#' 
plot_prot_spneedcat  <- function(progres,
                                    ctr, 
                                    ridl = "data-should-be-on-ridl",
                                    thisyear = 2021 ) { 
  
  

 Individual <- as.data.frame(progres[1] ) 
 SpecificNeed <-  as.data.frame(progres[14] )
 RegistrationGroup <- as.data.frame(progres[2] )
  RegistrationGroupall <-  as.data.frame(progres[17])

p <- SpecificNeed |> 
  dplyr::left_join( y = Individual,
                    by = c("IndividualID")) |> 
  dplyr::group_by( RegistrationGroupID, SpecificNeedSub   ) |> 
  dplyr::summarise(n = dplyr::n()) |> 
 dplyr::filter( ! (is.na(SpecificNeedSub) ))  |> 
 dplyr::filter( ! (is.na(RegistrationGroupID) ))   |> 
  dplyr::group_by( SpecificNeedSub  ) |> 
  dplyr::summarise(uniquecase = dplyr::n())  |>    
  dplyr::arrange(desc(uniquecase)) |>
  head(15)  |> 

  dplyr::left_join(SpecificNeed |> 
                     dplyr::left_join( y = Individual,
                                       by = c("IndividualID")) |> 
                     dplyr::group_by( RegistrationGroupID, SpecificNeedSub   ) |> 
                     dplyr::summarise(n = dplyr::n()) |> 
                    dplyr::filter( ! (is.na(SpecificNeedSub) ))  |> 
                    dplyr::filter( ! (is.na(RegistrationGroupID) ))   |> 
                     dplyr::group_by( SpecificNeedSub  ) |> 
                     dplyr::summarise(totalind = sum(n))
  ) |> 
  dplyr::mutate(avgindpercase = totalind/uniquecase)   |>
  mutate(uniquecase = as.numeric(uniquecase), 
       nRound =  ifelse(uniquecase > 1000, 
                        paste(scales::label_number_si(accuracy = 0.1)(uniquecase)),
                        as.character(uniquecase) ) ) |>  
  ggplot( aes(x = reorder(SpecificNeedSub,uniquecase), 
              y = uniquecase )) + 
  geom_bar(stat = "identity", 
           fill = "#0072bc") + 
  coord_flip() + 
  scale_y_continuous( label = scales::label_number_si() ) + 
  ## Position label differently in the bar in white - outside bar in black
  geom_label( data =   function(x) subset(x, uniquecase < max(uniquecase) / 1.5),
              aes(x = reorder(SpecificNeedSub, uniquecase),
                  y = uniquecase,
                  label= nRound),
              hjust = -0.1 ,
              vjust = 0.5, 
              colour = "black", 
              fill = NA, 
              label.size = NA, 
              family = "Lato", 
              size = 4   ) +  
  
  geom_label( data =   function(x) subset(x, uniquecase >= max(uniquecase) / 1.5),
              aes(x = reorder(SpecificNeedSub, uniquecase),
                  y = uniquecase,
                  label= nRound),
              hjust = 1.1 ,
              vjust = 0.5, 
              colour = "white", 
              fill = NA, 
              label.size = NA, 
              family = "Lato", 
              size = 4   ) +   
  geom_hline(yintercept = 0, size = 1.1, colour = "#333333") +
  unhcrthemes::theme_unhcr( font_size= 18)  +  
  theme(panel.grid.major.x  = element_line(color = "#cbcbcb"), 
        panel.grid.major.y  = element_blank(), 
        panel.grid.minor = element_blank()) + 
  labs(title = paste0("What are the main occurence of Specific Needs at case level in ", ctr, "?"),
       subtitle = paste0("Among the ", scales::label_comma()(nrow(RegistrationGroup)),
                         " case records, ",
                         scales::label_comma(accuracy = .1)(nrow(RegistrationGroupall |>dplyr::filter(countneed =="FALSE")) / nrow(RegistrationGroupall ) *100) ,
                         " % of cases have no single associated records of specific needs"),   
       x = "",
       y = "",
       caption = paste0("Source: Data available in RIDL @ ", ridl ,  "\n",
         str_wrap( 
         "This chart presents only the top 15 most frequent specific needs - type and subtype - measured in terms of occurence at case level (i.e. at least one record). One Individual can have more than one specific needs.",
           180) )) 

 return(p)

}

