# WARNING - Generated by {fusen} from /dev/flat_full.Rmd: do not edit by hand

#' @title Assemble all data components in a list and compute indicators
#' @description The function compute a summary chart 
#' @param progres   a list with all required frame re-encoded
#' @param ctr Country or Business Unit for the dataset dump
#' @param year Year of reference
#' @param ridl  name of the project in ridl.unhcr.org, the internal UNHCR repository based on CKAN
#' @return a list with both a ggplot2 crafted chart and the summary data
#' @export 
#'
#'

#' @examples
#' 
#' progresobj <- data_load(dataraw = system.file("demo/", package = "proGresAnalysis") )
#' progres <- data_recode(progresobj = progresobj,  ctr = "Ecuador")
#' plot_reach_agepyr (progres = progres , 
#'                          ctr = "Ecuador", 
#'                          ridl = "data-should-be-on-ridl" ,
#'                          thisyear = 2021)
#' 
plot_reach_agepyr <- function(progres,
                                    ctr, 
                                    ridl = "data-should-be-on-ridl" ,
                                    thisyear = 2021) { 
#install.packages("idbr")
library("idbr")
#idbr::idb_api_key('Your API key goes here')
idbr::idb_api_key(Sys.getenv("CENSUS"))

#names(Individual)
#table(Individual$Age, useNA= "ifany")

# https://stackoverflow.com/questions/15816073/population-pyramid-w-projection-in-r
# https://stackoverflow.com/questions/14680075/simpler-population-pyramid-in-ggplot2/36804394#36804394
#thisyear <- 2021


Individual <- as.data.frame(progres[1] ) 
pyramid_data <- idbr::get_idb(
  country = ctr,
  year = thisyear,
  age = 0:100,
  sex = c("male", "female"))  |> 
  mutate(Source = "Census") |>
  mutate(Age = age) |>
  mutate(Sex = sex) |>
  dplyr::select(Age, Sex, pop, Source)

pyramid_data1 <- Individual |> 
  filter( ! (is.na(Age) )) |> 
  dplyr::group_by(Age , Sex  ) |> 
  dplyr::summarise(pop= n()) |> 
  filter( ! Sex %in% c("Other","Unknown") )  |> 
  mutate(Source = "Registered") |>
  bind_rows(pyramid_data)|> 
  group_by(Source) |> 
  mutate(popprop = round( pop/sum(pop) *100 , 3))|> 
  filter( Age <= 101 ) 

p<- ggplot(data = pyramid_data1, aes(x = Age, 
                       y = popprop , 
                       fill = Sex)) +
  
  #bars for all but 2030
  geom_bar(data = pyramid_data1 |> 
             filter(Sex == "Female",
                    Source == "Registered" ),
           stat = "identity",
           position = "identity") + 
  
  geom_bar(data = pyramid_data1 |> 
             filter(Sex == "Male", 
                    Source == "Registered" ),
           stat = "identity",
           position = "identity",
           mapping = aes(y = -popprop)) +
  
  #steps for 2030
  geom_step(data =  pyramid_data1 |> 
              filter(Sex == "Female", 
                     Source == "Census"), 
            aes(x = Age ,
                y = popprop  )) +
  
  geom_step(data =  pyramid_data1 |> 
              filter(Sex == "Male", 
                     Source == "Census"), 
            aes(x = Age, 
                y = -popprop)) +
  
  coord_flip() +
  guides(fill="none") + 
  scale_y_continuous(labels = abs) +
  scale_colour_manual(values = c("#126db4","#01ab91"),
                      aesthetics = c("colour", "fill")) +
  geom_hline(yintercept = 0, size = 1.1, colour = "#333333") +
  unhcrthemes::theme_unhcr( font_size= 18)  +  
  theme(panel.grid.major.y  = element_line(color = "#cbcbcb"), 
        panel.grid.major.x  = element_blank(), 
        panel.grid.minor = element_blank()) + 
  labs(title = "How Much Age & Gender of Registered Population Differ from Host Population?",
       subtitle = paste0("Comparing profiles between registered and host population (black lines) in ", ctr),   
       x = "Age Bracket",
       y = "As % of total population",
       caption = paste0("Source: Data available in RIDL @ ", ridl, " compared with baseline demographic profile for the host population - source US Census Bureau ") ) + 
  
    ggtext::geom_textbox(data = data.frame(x = 96, y = -0.52, 
                                           label = "Male"),
                        mapping = aes(x = x, y = y, label = label),
                        width = unit(0.2, "npc"),
                        family = "Lato", size = 5, fill = "#01ab91",
                        inherit.aes = FALSE) +
    ggtext::geom_textbox(data = data.frame(x = 96, y = 0.52, 
                                           label = "Female"),
                        mapping = aes(x = x, y = y, label = label),
                        width = unit(0.2, "npc"),
                        family = "Lato", size = 5, fill = "#126db4",
                        inherit.aes = FALSE)
 return(p) 
  ## Add annotation -- use ggannotate to get the right  coordinate within chart
  #remotes::install_github("mattcowgill/ggannotate")
  #ggannotate::ggannotate()
  
  # geom_curve(aes(xend = 10.9476141263782, yend = 2959.93589579213, 
  #                x = 6.91965137456717, y = 28668.752697603),
  #            size = 2, color = "tan",
  #            arrow = arrow(length = unit(0.07, "npc"))) +
  # ggtext::geom_textbox(data = data.frame(x = 6.91965137456717, y = 28668.752697603, 
  #                                        label = "Why so many people are using **other** category? \n Is there an important missing category within Primes?"),
  #                     mapping = aes(x = x, y = y, label = label),
  #                     width = unit(0.6, "npc"),
  #                     family = "Lato", size = 7, fill = "cornsilk",
  #                     inherit.aes = FALSE)


# : Is it the same as the local population? Does it coincide with the data from the country of origin? If one group, such as adult men or young children, seems under- or over-represented, find out why.

}


#' @title Analytic chart to display registration coverage
#' @description The function compute a summary chart 
#' @param progres   a list with all required frame re-encoded
#' @param ctr Country or Business Unit for the dataset dump
#' @param year Year of reference
#' @param ridl  name of the project in ridl.unhcr.org, the internal UNHCR repository based on CKAN
#' @return a list with both a ggplot2 crafted chart and the summary data
#' @export 
#'
#'

#' @examples
#' 
#' progresobj <- data_load(dataraw = system.file("demo/", package = "proGresAnalysis") )
#' progres <- data_recode(progresobj = progresobj,  ctr = "Ecuador")
#' plot_reach_registration (progres = progres , 
#'                          ctr = "Ecuador", 
#'                          ridl = "Ecuador",
#'                                     thisyear = 2021)
plot_reach_registration <- function(progres,
                                    ctr, 
                                    ridl = "data-should-be-on-ridl",
                                    thisyear = 2021 ) {

   Individual <- as.data.frame(progres[1] ) 
   popdatactr <- as.data.frame(progres[18] ) 
  
    
## get popdata report in order to have comparison by legal status
p <- Individual |> 
  dplyr::group_by( LegalStatus  ) |> 
  dplyr::summarise(n = dplyr::n()) |> 
  filter( ! (is.na(LegalStatus) )) |> 
  mutate(n = as.numeric(n), 
         ValRound =  ifelse(n > 1000, 
                          paste(scales::label_number_si(accuracy = 0.1)(n)),
                          as.character(n) ) )   |>
  dplyr::left_join( y= popdatactr, 
                    by = c("LegalStatus" = "LegalStatus"))  |> 
  mutate(notregistered =  as.integer(ifelse(is.na(totalasr), 0, paste(totalasr - n) ))) |> 
  mutate(coverage =  ifelse(is.na(totalasr), 
                        paste0(ValRound, " registered, not published as Stat"),
                        paste0(ValRound, " registered, ", scales::label_number_si(accuracy = 0.1)(n/totalasr *100), 
                               " % of total Stat")) )   |> 
  dplyr::select(LegalStatus, coverage, notregistered, n )  |> 
  tidyr::pivot_longer(
    cols = starts_with("n"), # "LegalStatus", "coverage"
    names_to = "datarecord", 
    values_to = "ind"
  )   |>
  ggplot( aes(x = reorder(LegalStatus, ind),
              y = ind,
              fill = datarecord)) + 
  geom_bar(stat = "identity", 
           position = "stack"
           # fill = "#0072bc"
  ) + 
  coord_flip() + 
  scale_y_continuous( label = scales::label_number_si() ) +
  scale_fill_manual(values = c( "blue", "gray"))+ 
  guides(fill="none") + 
  ## Position label differently in the bar in white - outside bar in black
  geom_label( data =   function(x) subset(x, ind < max(ind) / 1.5 &
                                            datarecord =="notregistered"),
              aes(x = reorder(LegalStatus, ind),
                  y = ind,
                  label= coverage),
              hjust = -0.1 ,
              vjust = 0.5, 
              colour = "black", 
             # position = position_stack(vjust= 0.5),
              fill = NA, 
              label.size = NA, 
              family = "Lato", 
              size = 4   ) +  
  
  geom_label( data =   function(x) subset(x, ind >= max(ind) / 1.5  &
                                            datarecord =="notregistered" ),
              aes(x = reorder(LegalStatus, ind),
                  y = ind,
                  label= coverage),
              hjust = 1.1 ,
              vjust = 0.5, 
              colour = "white", 
             # position = position_stack(vjust= 0.5),
              fill = NA, 
              label.size = NA, 
              family = "Lato", 
              size = 4   ) +    
  geom_hline(yintercept = 0, size = 1.1, colour = "#333333") +
  unhcrthemes::theme_unhcr( font_size= 18)  +  
  theme(panel.grid.major.x  = element_line(color = "#cbcbcb"), 
        panel.grid.major.y  = element_blank(), 
        panel.grid.minor = element_blank() ) + 
  labs(title = "What is the share among the total people of concern that is registered with UNHCR?",
       subtitle = paste0("Assessing gap between Annual Statistical Reports (grey) with Active registered Cases (Blue) in " , ctr),   
       x = "",
       y = "",
       caption = paste0("Source: Data available in RIDL @ ", ridl, "compared with extract from Internal Annual Statistical Report from http://popdata.unhcr.org.\n There might be situation where the numbe of registered individual is higher than numbers reported as official statistics. That (grey) excedent will then appear as negative.") )

return(p)

  ## Add annotation -- use ggannotate to get the right  coordinate within chart
  #remotes::install_github("mattcowgill/ggannotate")
  #ggannotate::ggannotate()
  
  # geom_curve(aes(xend = 10.9476141263782, yend = 2959.93589579213, 
  #                x = 6.91965137456717, y = 28668.752697603),
  #            size = 2, color = "tan",
  #            arrow = arrow(length = unit(0.07, "npc"))) +
  # ggtext::geom_textbox(data = data.frame(x = 6.91965137456717, y = 28668.752697603, 
  #                                        label = "Why so many people are using **other** category? \n Is there an important missing category within Primes?"),
  #                     mapping = aes(x = x, y = y, label = label),
  #                     width = unit(0.6, "npc"),
  #                     family = "Lato", size = 7, fill = "cornsilk",
  #                     inherit.aes = FALSE)
 }



#' @title Assemble all data components in a list and compute indicators
#' @description The function compute a summary chart 
#' @param progres   a list with all required frame re-encoded
#' @param ctr Country or Business Unit for the dataset dump
#' @param year Year of reference
#' @param ridl  name of the project in ridl.unhcr.org, the internal UNHCR repository based on CKAN
#' @return a list with both a ggplot2 crafted chart and the summary data
#' @export 
#'
#'

#' @examples
#' progresobj <- data_load(dataraw = system.file("demo/", package = "proGresAnalysis") )
#' progres <- data_recode(progresobj = progresobj,  ctr = "Ecuador")
#' plot_reach_return(progres  = progres , 
#'                          ctr = "Ecuador", 
#'                          ridl = "data-should-be-on-ridl" ,
#'                                     thisyear = 2021 )
plot_reach_return <- function(progres,
                                    ctr, 
                                    ridl = "data-should-be-on-ridl",
                                    thisyear = 2021 ) { 
#names(RegistrationGroup)
#table(RegistrationGroup$WillingToReturn, useNA= "ifany")
  
  
    

    Individual <- as.data.frame(progres[1] ) 
    RegistrationGroup <- as.data.frame(progres[2] )
    
if( nlevels(as.factor(RegistrationGroup$WillingToReturn)) > 0 ) {
p <- RegistrationGroup |> 
  dplyr::mutate( WillingToReturn = dplyr::if_else( is.na(WillingToReturn) ,
                                                   paste0("No info recorded"), 
                                                   WillingToReturn)  ) |>
  dplyr::left_join( y = Individual) |> 
    dplyr::group_by( RegistrationGroupID, WillingToReturn,CountryOfOriginCat   ) |> 
    dplyr::summarise(Origin = dplyr::n())  |> 
   dplyr::filter( ! (is.na(RegistrationGroupID) ))  |>
    tidyr::pivot_wider(names_from  = CountryOfOriginCat,
                       names_glue = "{.value}_{CountryOfOriginCat}",
                       values_from = Origin) |> 
  #replace(is.na(.), 0) |>
  dplyr::mutate( dplyr::across(where(is.integer), ~ tidyr::replace_na(.x, 0)) ) |>
  #  dplyr::mutate(dplyr::across(everything(), ~ replace_na(.x, 0))) |>
  dplyr::mutate(dplyr::across( where(is.integer), ~ dplyr::if_else( .x > 0 , TRUE,FALSE) ) )  |>
 
  tidyr::pivot_longer(
    cols = starts_with("Origin"),
    names_to = "Orig",
    names_prefix = " ",
    values_to = "cases",
    values_drop_na = TRUE ) |> 
  dplyr::filter( cases == "TRUE" ) |>
  
  dplyr::group_by(WillingToReturn, Orig ) |> 
  dplyr::summarise(n = dplyr::n())   |> 
  mutate(n = as.numeric(n), 
         nRound =  ifelse(n > 1000, 
                          paste(scales::label_number_si(accuracy = 0.1)(n)),
                          as.character(n) ) ) |>  
  ggplot( aes(x = reorder(WillingToReturn,n), 
              y = n )) + 
  geom_bar(stat = "identity", 
           fill = "#0072bc") + 
  facet_grid(. ~ Orig ) +
  coord_flip() + 
  scale_y_continuous( label = scales::label_number_si() ) + 
  ## Position label differently in the bar in white - outside bar in black
  geom_label( data =   function(x) subset(x, n < max(n) / 1.5),
              aes(x = reorder(WillingToReturn, n),
                  y = n,
                  label= nRound),
              hjust = -0.1 ,
              vjust = 0.5, 
              colour = "black", 
              fill = NA, 
              label.size = NA, 
              family = "Lato", 
              size = 4   ) +  
  geom_label( data =   function(x) subset(x, n >= max(n) / 1.5),
              aes(x = reorder(WillingToReturn, n),
                  y = n,
                  label= nRound),
              hjust = 1.1 ,
              vjust = 0.5, 
              colour = "white", 
              fill = NA, 
              label.size = NA, 
              family = "Lato", 
              size = 4   ) +   
  geom_hline(yintercept = 0, size = 1.1, colour = "#333333") +
  unhcrthemes::theme_unhcr( font_size= 18)  +  
  theme(panel.grid.major.x  = element_line(color = "#cbcbcb"), 
        panel.grid.major.y  = element_blank(), 
        panel.grid.minor = element_blank()) + 
  labs(title = "What are the intentions in terms of return by Country of Origin?",
       subtitle = paste0("Among the ", scales::label_comma()(nrow(RegistrationGroup)),
                         " case records, ",
                         scales::label_comma()(nrow(RegistrationGroup |>dplyr::filter( !(is.na(WillingToReturn) )))),
                         " includes information on this topic in ", ctr),   
       x = "",
       y = " ",
       caption = paste0("Source: Data available in RIDL @ ", ridl, "\n",
                        "Only nationality with a frequency over 10% are included. Note that this information is collected at case level.") )
  
  return(p)
  
} else {
  #cat("There's not a single records of intention within the registration database")
  return( cat("There's not a single records of intention within the registration database"))
}

}
